### PR TITLE
Fix/bouncing bug

### LINKED ISSUE #91: Strange velocity 'bouncing' behaviour with SPEC
Platform: Linux
Using the latest master (vssetup identifies as 0.6.0)

Sometimes (about 50% of the time? It's hard to say), when using Auto-pilot to approach or leave a major object, the ship's velocity will not behave properly. It will rapidly 'bounce' between seemingly random velocities from the hundreds range to the tens of thousands. During this, the positions of major objects also seem to bounce, but maybe this is only an illusion due to the rapid velocities involved?

This will continue to happen even after auto is turned off, making it essentially impossible to control your vessel. The effect can sometimes be calmed by switching to another target, but it will come back. This is while auto pilot is off, so targeting different objects shouldn't affect my control. I have tested using "default", "realistic", and "classic" physics, and it can occur on all three modes.

Flying close to a major object using autopilot and then switching targets seems especially likely to trigger this. I can provide additional information if needed, or record a video

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [x] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
- Please list any related issues
Fixes #91 

Purpose:
- What is this pull request trying to do? Fix the bouncing bug!
- What release is this for? 0.7.0
- Is there a project or milestone we should apply this to? 0.7.x

### CODE REVIEW

File: engine/src/gfx/tvector.cpp [hunk 1]
```diff
@@ -39,7 +39,7 @@ float _sqrt(float f) {
 
 template <>
 double _sqrt(double d) {
-  return sqrtf(d);
```
Comment (BenjamenMeyer) [inline engine/src/gfx/tvector.cpp:42]: That would make a difference

Comment (stephengtuggy) [reply engine/src/gfx/tvector.cpp:42]: Yep

**Comment by stephengtuggy** [comment]
This code may be messy, but it does seem to fix the bouncing bug. What do you guys think? Should I clean it up a little bit more, or shall we merge it in like this?

More testing **is** still needed, to see if too many physics calculations pile up on top of each other with the "Current computer" setting. Especially in the "Sol" system. If so, we might need to run the game at a slightly lower setting.

That reminds me. When you change the "Current computer" setting to a lower setting in vegasettings, it doesn't seem to comment out the corresponding simulation_atom setting correctly in the config file. So I am attaching my config file, in case it helps you test.

**Comment by stephengtuggy** [comment]
[vegastrike_config_SGT_2020-07-24.zip](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/4974676/vegastrike_config_SGT_2020-07-24.zip)

**Comment by stephengtuggy** [comment]
During my play testing, the camera zoomed in and out suddenly on the background a few times, but that could have been explainable by passing ships interfering with SPEC/the autopilot. None of the objects or other units bounced back and forth that I noticed.

File: engine/src/cmd/unit_util_generic.cpp [hunk 2]
```diff
@@ -78,8 +78,8 @@ bool hasDockingUnits( const Unit *my_unit )
 
 int getPhysicsPriority( Unit *un )
 {
-    static const bool FORCE_TOP_PRIORITY = XMLSupport::parse_bool(
-        vs_config->getVariable( "physics", "priorities", "force_top_priority", "false" ) );
+    static const bool FORCE_TOP_PRIORITY = true; //XMLSupport::parse_bool(
+        //vs_config->getVariable( "physics", "priorities", "force_top_priority", "false" ) );
```
Comment (BenjamenMeyer) [inline engine/src/cmd/unit_util_generic.cpp:82]: This could probably just `bool FORCE_TOP_PRIORITY` or `const bool FORCE_TOP_PRIORITY` for its type; it's only used in this function. `static` is unnecessary.

Not a blocker, just noting it.

File: engine/src/cmd/unit.cpp [hunk 3]
```diff
@@ -381,7 +381,7 @@ void GameUnit< UnitType >::Draw( const Transformation &parent, const Matrix &par
     if (!cam_setup_phase) {
         // Following stuff is only needed in actual drawing phase
         if (this->cloaking > this->cloakmin) {
-            cloak = (int) (this->cloaking-interpolation_blend_factor*this->pImage->cloakrate*simulation_atom_var);
+            cloak = (int) (this->cloaking-interpolation_blend_factor*this->pImage->cloakrate * SIMULATION_ATOM /*simulation_atom_var*/ );
```
Comment (BenjamenMeyer) [inline engine/src/cmd/unit.cpp:384]: I assume all the `/*simulation_atom_var*/` is just documentation about `SIMULATION_ATOM`

Comment (stephengtuggy) [reply engine/src/cmd/unit.cpp:384]: No, it's an alternative variable with the same initial value, but one that looks like maybe it's meant to be changed -- unlike the one in ALL_CAPS.

File: engine/src/cmd/unit_util_generic.cpp (hunk 2 above)
Comment (stephengtuggy) [reply engine/src/cmd/unit_util_generic.cpp:82]: If it was just `bool FORCE_TOP_PRIORITY`, it would probably read the setting correctly, after vs_config is initialized properly with the values from the file. Maybe I should just do that.

File: engine/src/cmd/unit.cpp (hunk 3 above)
Comment (stephengtuggy) [reply engine/src/cmd/unit.cpp:384]: These are places where I was using the lowercase one in an intermediate commit.

Comment (BenjamenMeyer) [reply engine/src/cmd/unit.cpp:384]: @stephengtuggy okay - so then let's either:
- wrap these in a #define so to switch between them, or 
- if not needed clean them up

so we don't confuse people

File: engine/src/lin_time.cpp [hunk 4]
```diff
@@ -149,7 +150,8 @@ void micro_sleep( unsigned int n )
 
 #elif defined (IRIX)
 
-#include <unistd.h>
+// Now included above, for all operating systems except Windows
+// #include <unistd.h>
```
Comment (BenjamenMeyer) [inline engine/src/lin_time.cpp:154]: yes we need to clean a lot of this up; feel free to just drop it out entirely.

NOTE: FTR Only time a header should be included lower in a file is if there's a define that changes it as a result, even then we should try to keep as much of that at the top as possible.

**Comment by evertvorster** [comment]
I have done some play testing on this PR, too. 
I'd say this one cures the bouncing bug, and puts my play testing on the master branch. I will of course do more play testing, but I have visited a handful of bases all over the Universe, including Sol/Sol, and the game performs beautifully.

**Comment by stephengtuggy** [comment]
> I have done some play testing on this PR, too.
> I'd say this one cures the bouncing bug, and puts my play testing on the master branch. I will of course do more play testing, but I have visited a handful of bases all over the Universe, including Sol/Sol, and the game performs beautifully.

Awesome.

What simulation_atom setting did you use in your tests? Did you use the vegastrike.config I provided, with the lower/older setting, or did you use the "Current computer" setting, as vegasettings refers to it?

**Comment by stephengtuggy** [comment]
So I just tested test/9k_idle_1k_fighting.mission, with simulation_atom 0.01 ("Current Computer"), resolution 3800x2000 (near 4K), and --debug=3, no less. Everything seemed to work fine.

I think this PR is ready to merge.

**Comment by stephengtuggy** [comment]
Hold on, I take that back.

**Comment by Loki1950** [comment]
Glad you still looking for the underling reason.

**Comment by stephengtuggy** [comment]
Well, guys. This latest patch is looking pretty promising. It passes the "bouncing" test; it passes the 9k_idle_1k_fighting test; and it appears to pass soltest as well.

Let me know what you think.

File: engine/src/lin_time.cpp (hunk 4 above)
Comment (stephengtuggy) [reply engine/src/lin_time.cpp]: Dropped entirely.

File: engine/src/cmd/unit.cpp (hunk 3 above)
Comment (stephengtuggy) [reply engine/src/cmd/unit.cpp]: I believe `simulation_atom_var` is the correct one to use in most cases, so I have made that change.

File: engine/src/cmd/unit_util_generic.cpp (hunk 2 above)
Comment (stephengtuggy) [reply engine/src/cmd/unit_util_generic.cpp]: Took out the `const` clause. Now it reads its value correctly from the config file.

**Comment by evertvorster** [comment]
I have played with it some as well, and I like how smooth everything is. Have not noticed anything untoward while approaching quite a few bases.

**Comment by stephengtuggy** [comment]
The major changes are:

- In lin_time.cpp, uses `clock_gettime` to get the system time, where this function is available
- Corrects a couple of minor potential precision issues with the (Q)Vector refactor
- Switches to using `simulation_atom_var` (variable naming convention) instead of `SIMULATION_ATOM` (constant naming convention) in most places
- Disables randomization of physics priority (per-unit sim_atom), controlled by a compile-time `#define`
- Gives all system installations a fixed physics priority, defaulting to 3 (planets, asteroids, bases, and such)
- Changes various `static const` declarations of config file variables to just `static`, so that they will actually pick up their values from the vegastrike.config file. One of these is force_top_priority, which forces all units/objects to run at priority 1 when set.
- Makes a few other changes that mean that individual units will change priority less often
