### PR TITLE
Fix bug 1411 - purchase of cargo was crashing

### LINKED ISSUE #1411: Unable to buy armor
This has been an issue for a while. In the upgrade screen, when I click on an armor entry and click Buy, nothing happens -- at least nothing visible in the game window.

I would like to see this fixed.

### PR DESCRIPTION
**Pull request by royfalk**
as volume was 0 and there was a div by 0 error.

Closes #1411 

**Code Changes:**
- [ ] Have the PR Validation Tests been run? _No. Just the bug fix._

### CODE REVIEW

File: engine/src/components/components_manager.cpp [hunk 1]
```diff
@@ -341,10 +341,12 @@ bool ComponentsManager::_Buy(CargoHold *hold, ComponentsManager *seller, Cargo *
...
     quantity = std::min(max_affordable_quantity, quantity);
 
-    // Check the maximum you can fit in your hold
-    int max_stackable_quantity = static_cast<int>(std::floor(hold->AvailableCapacity() / item->GetVolume()));
-    quantity = std::min(max_stackable_quantity, quantity);
-
+    // Check the maximum you can fit in your hold, but only if volume != 0
+    if(item->GetVolume() > 0) {
+        int max_stackable_quantity = static_cast<int>(std::floor(hold->AvailableCapacity() / item->GetVolume()));
+        quantity = std::min(max_stackable_quantity, quantity);
```
Comment (BenjamenMeyer) [inline engine/src/components/components_manager.cpp:347]: shouldn't this also have a `std::max` with `0` so it doesn't go negative?

Comment (royfalk) [reply engine/src/components/components_manager.cpp:347]: So this is a bit complex. We have a 'mult_shady_moreupgrade' upgrade, which could show up as negative volume but for now is implemented as volume=0.1. 
In reality, if we have a negative volume for actual upgrades, this will have issues elsewhere as well.
Better to fix this properly in cargo.

**Comment by royfalk** [comment]
Last commit belongs in task_fix_1488. Reverting.

File: engine/src/components/components_manager.cpp (hunk 1 above)
Comment (BenjamenMeyer) [reply engine/src/components/components_manager.cpp:347]: while I agree we should fix it elsewhere too, we should also protect ourselves here as well.

Comment (royfalk) [reply engine/src/components/components_manager.cpp:347]: OK. Fixed cargo class to prevent any option of negative or zero mass or volume.
If there's a need for some exception, we can revisit the issue.

File: engine/src/resource/cargo.cpp [hunk 2]
```diff
@@ -47,6 +47,11 @@ static bool _parse_bool(const std::string& value) {
     return (value == "1" || value == "true");
 }
 
+// A simple utility function to prevent zero or negative mass and volume
+static double at_least_tenth(double input) {
+    return input > 0 ? input : 0.1;
```
Comment (BenjamenMeyer) [inline engine/src/resource/cargo.cpp]: `input > 0.1` would probably be best since `input > 0` would be true even if `input` was `0.000000000000001` - essentially the zero value for the type.

Keep in mind that floating point (float/double) do not store exactly zero - it can be `0.000000001` or `-0.9999999999999` (number of zeros/nines is dependent on the type).

**Review by BenjamenMeyer — CHANGES_REQUESTED** [review]
I get what you're trying to do, but I don't think the code quite gets there since it doesn't do an accurate check for a zero value of a double-precision type.

**Comment by kheckwrecker** [comment]
I can think of one possible exception - in the campaign, it may be possible that you get asked to transport something with zero mass for game play purposes. I'm thinking of, for example, the plot mission in Privateer where you're asked to hide the alian artifact  in a "secret hold" on your ship. As I recall, that artifact had zero mass, so that it had no effect on your ability to take on cargo runs, while you held onto the artifact.

File: engine/src/resource/cargo.cpp (hunk 2 above)
Comment (royfalk) [reply engine/src/resource/cargo.cpp]: I am aware of this and was actually being intentional here.
if input == 0.00001, input > 0, use this value. I assume the game designers know what they're doing.
If input <= 0, even if the game designers intended this, I can't allow this and default to a small number. For volume and mass, 0.1 is a reasonable number to plug here.
Reasonable in the sense that buying/selling cargo will be reflected in the shop mass and volume.

**Comment by royfalk** [comment]
> I can think of one possible exception - in the campaign, it may be possible that you get asked to transport something with zero mass for game play purposes. I'm thinking of, for example, the plot mission in Privateer where you're asked to hide the alian artifact in a "secret hold" on your ship. As I recall, that artifact had zero mass, so that it had no effect on your ability to take on cargo runs, while you held onto the artifact.

You're confusing mass and volume and the secret hold is a separate hold.
"file": "Halogen_Gases", "mass": "1.2", "volume": "25". If you fill your Llama with it, you'll have 40 units weighing 48 tons.
"file": "Gold", "mass": "19", "volume": "1". 1000 units and 19k tons.
There's no reason for the alien artifact to be 0 mass or even 0 volume.

Originally, there was one hold for upgrades, cargo and secret cargo. As a result, the game was filled with code to check what we're dealing with and where it is. Now that we've separated the holds, this is much simpler. But even then, the secret hold had a volume.

When we port this version to WC, or rather WC to this version, we'll need to check the secret hold code. I'm not sure it works properly, as I haven't tested it.

File: engine/src/resource/cargo.cpp (hunk 2 above)
Comment (BenjamenMeyer) [reply engine/src/resource/cargo.cpp]: Please update the comment to note then since as I mentioned `0.0000000000...1` could still be zero.

**Comment by BenjamenMeyer** [comment]
> > I can think of one possible exception - in the campaign, it may be possible that you get asked to transport something with zero mass for game play purposes. I'm thinking of, for example, the plot mission in Privateer where you're asked to hide the alian artifact in a "secret hold" on your ship. As I recall, that artifact had zero mass, so that it had no effect on your ability to take on cargo runs, while you held onto the artifact.
> 
> You're confusing mass and volume and the secret hold is a separate hold. "file": "Halogen_Gases", "mass": "1.2", "volume": "25". If you fill your Llama with it, you'll have 40 units weighing 48 tons. "file": "Gold", "mass": "19", "volume": "1". 1000 units and 19k tons. There's no reason for the alien artifact to be 0 mass or even 0 volume.
> 
> Originally, there was one hold for upgrades, cargo and secret cargo. As a result, the game was filled with code to check what we're dealing with and where it is. Now that we've separated the holds, this is much simpler. But even then, the secret hold had a volume.
> 
> When we port this version to WC, or rather WC to this version, we'll need to check the secret hold code. I'm not sure it works properly, as I haven't tested it.

@kheckwrecker is correct regarding the original Privateer game - they did write it as having `zero mass` and it shows up that way in the manifest for the game, which I think was to not have it impact anything performance wise of the ship and not take up cargo space for how that game functioned. IIRC it also did not impact your inventory for what your ship could carry so you could use any kind of ship regardless of how full it was with cargo to complete the mission.

That said, I also agree with @royfalk  in that it could still work here even if the mass is extremely small or it uses the secret hold to accommodate. So I don't think we're losing anything, just changing how the mechanism would work to recreate the scenario.

File: engine/src/resource/cargo.cpp (hunk 2 above)
Comment (royfalk) [reply engine/src/resource/cargo.cpp]: As in 
`// A simple utility function to prevent (close to) zero or negative mass and volume`
?

Comment (stephengtuggy) [reply engine/src/resource/cargo.cpp]: `at_least_tenth` doesn't do what it says it does. Please, let's either rename it to something like `greater_than_zero`, or change the implementation to not allow any value less than 0.1.

Comment (royfalk) [reply engine/src/resource/cargo.cpp]: Pushed a new commit. Let's continue the discussion after it.

**Comment by royfalk** [comment]
I was never happy with the naming of the function. I finally realised it's basically a max function, so I replaced it with one.
I did move the constructor parameters from float to double. The class members themselves are all double already, so it should be fine. I think it's ready for a last review.

**Comment by stephengtuggy** [comment]
I like this latest version. It's elegant and clean. I'm sure it will "just work."
