### PR TITLE
Joystick settings, 2nd round

### LINKED ISSUE #1196: Migrate `joystick` settings section to new mechanism

### LINKED ISSUE #1301: Make install does not work on git master.
I get this error:
```
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /home/evert/Aur/vegastrike-engine-git/pkg/vegastrike-engine-git/usr/bin/vega-meshtool
-- Installing: /home/evert/Aur/vegastrike-engine-git/pkg/vegastrike-engine-git/usr/bin/vegastrike-engine
-- Installing: /home/evert/Aur/vegastrike-engine-git/pkg/vegastrike-engine-git/usr/bin/vegastrike
-- Installing: /home/evert/Aur/vegastrike-engine-git/pkg/vegastrike-engine-git/usr/share/doc/Vega_Strike/AUTHORS.SF
-- Installing: /home/evert/Aur/vegastrike-engine-git/pkg/vegastrike-engine-git/usr/share/doc/Vega_Strike/AUTHORS.GITHUB
CMake Error at engine/doc/cmake_install.cmake:54 (file):
  file INSTALL cannot find
  "/home/evert/Aur/vegastrike-engine-git/src/Vega-Strike-Engine-Source/Engine-API.md":
  No such file or directory.
Call Stack (most recent call first):
  engine/cmake_install.cmake:76 (include)
  cmake_install.cmake:52 (include)


make: *** [Makefile:120: install] Error 1
make: Leaving directory '/home/evert/Aur/vegastrike-engine-git/src/build'
```

Looks like the fix is fairly easy, here are some clues:
```
evert@Evert ~/A/v/s/Vega-Strike-Engine-Source (master)> find . | grep AUTHORS
./AUTHORS
./doc/AUTHORS
evert@Evert ~/A/v/s/Vega-Strike-Engine-Source (master)> find . | grep Engine-API
./doc/Engine-API.md
evert@Evert ~/A/v/s/Vega-Strike-Engine-Source (master)> 
```

So, there are two AUTHORS files, one in the source root and one in /doc. 
Which is the one we would like to install? It looks like the one in the source root is the one that was installed up to this point, and the one in /doc is wildly out of date.

### LINKED ISSUE #1303: Build failing with Boost 1.89.0
I think I just figured out how to fix our failing macOS builds. Boost 1.89.0, the latest release, no longer includes the "system" component. We had that component listed as one of our dependencies. But apparently it wasn't actually needed, because I removed it, and everything seems to be working still.

### PR DESCRIPTION
**Pull request by stephengtuggy**
Code Changes:
- [x] (Mostly) Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

Issues Addressed:
- Closes #1196 
- Fixes #1301 
- Fixes #1303 

Known Issues Remaining:
- None particularly

Purpose:
- What is this pull request trying to do? Convert the joystick settings to the new `configuration()` mechanism. Second try.
- What release is this for? 0.10.x
- Is there a project or milestone we should apply this to? 0.10.x

### CODE REVIEW

File: engine/src/force_feedback.cpp [hunk 1]
```diff
@@ -205,12 +205,12 @@ void ForceFeedback::stopEffect( unsigned int eff_nr )
...
 void ForceFeedback::init()
 {
-    if (!game_options()->force_feedback) {
+    if (!configuration().joystick.force_feedback) {
         VS_LOG(info, "force feedback disabled in config file");
         return;
     }
     char devname[200];
-    sprintf( devname, "/dev/input/event%d", game_options()->ff_device );
+    snprintf( devname, 199, "/dev/input/event%d", configuration().joystick.ff_device );
```
Comment (BenjamenMeyer) [inline engine/src/force_feedback.cpp]: should the `199` be a configuration option?

Comment (stephengtuggy) [reply engine/src/force_feedback.cpp]: I don't think so. If it was configurable, then theoretically, a bad actor could specify a huge amount of memory, and cause a Denial of Service or similar.

The specific value comes from the `200` two lines above, minus one for the final null character.

Comment (stephengtuggy) [reply engine/src/force_feedback.cpp]: Maybe it should be a constant, though, instead of a "magic number." Like `BUFFER_SIZE` or something.

Comment (stephengtuggy) [reply engine/src/force_feedback.cpp]: Changed to a constexpr named `BUFFER_SIZE`.

**Comment by evertvorster** [comment]
Make install does not work:
```
-- Installing: /home/evert/Aur/vegastrike-engine-git/pkg/vegastrike-engine-git/usr/share/doc/Vega_Strike/AUTHORS.GITHUB
CMake Error at engine/doc/cmake_install.cmake:54 (file):
  file INSTALL cannot find
  "/home/evert/Aur/vegastrike-engine-git/src/Vega-Strike-Engine-Source/Engine-API.md":
  No such file or directory.
Call Stack (most recent call first):
  engine/cmake_install.cmake:76 (include)
  cmake_install.cmake:52 (include)


make: *** [Makefile:120: install] Error 1
make: Leaving directory '/home/evert/Aur/vegastrike-engine-git/src/build'
```

**Comment by stephengtuggy** [comment]
@evertvorster Try it now. I just removed the explicit file path for Engine-API.md, and now it's working for me.

**Comment by stephengtuggy** [comment]
I think I also just figured out how to fix our failing macOS builds. Boost 1.89.0, the latest release, no longer includes the "system" component. We had that component listed as one of our dependencies. But apparently it wasn't actually needed, because I removed it, and everything seems to be working still.

File: engine/src/star_system_jump.cpp [hunk 2]
```diff
@@ -110,52 +110,55 @@ static unsigned int AddJumpAnimation(const QVector &pos, const float size, bool
...
+            float width;
+            float height;
+            jump_animation.a->GetDimensions(width, height);
+            jump_animation.a->SetDimensions(jump_animation.percent * width, jump_animation.percent * height);
+            if (!jump_animation.a->Done()) {
+                jump_animation.a->Draw();
             }
         }
     }
+    const auto first_to_remove = std::stable_partition(VolatileJumpAnimations.begin(), VolatileJumpAnimations.end(),
```
Comment (royfalk) [inline engine/src/star_system_jump.cpp:154]: I see you've taken this erase code out of the nest above. Could you please explain what you did and why.
The original code deleted the animation if it were done.
Now you're drawing if not done and then creating a partition of done animations and deleting them?!

File: engine/src/star_system_jump.cpp [hunk 3]
```diff
@@ -110,52 +110,55 @@ static unsigned int AddJumpAnimation(const QVector &pos, const float size, bool
...
-                VolatileJumpAnimations[i].a = nullptr;
-                VolatileJumpAnimations.erase(VolatileJumpAnimations.begin() + i);
-                --i;
-            } else {
-                VolatileJumpAnimations[i].a->Draw();
+    for (const auto& jump_animation : VolatileJumpAnimations) {
+        if (jump_animation.a) {
+            float width;
+            float height;
+            jump_animation.a->GetDimensions(width, height);
```
Comment (royfalk) [inline engine/src/star_system_jump.cpp:147]: I like the rename from VolatileJumpAnimation to jump_animation. Much clearer.

File: engine/src/star_system_jump.cpp (hunk 2 above)
Comment (stephengtuggy) [reply engine/src/star_system_jump.cpp:154]: The stable_partition with a negated Lambda condition sorts the elements in the collection, with the elements to be deleted towards the end, and the ones to keep towards the beginning. Then you can delete all the elements that need it, and then erase them all in a single, efficient operation.

Otherwise, this code should not change functionally at all.
