### PR TITLE
Fix 1525

### LINKED ISSUE #1525: Player turrets are broken
I've been refactoring something else and needed to check something with the turrets.
I flew a Vigilance - a ship with multiple turrets.
You can switch to the first turret using [.
However, you can't fire the turret or switch back.
Looking at the code, it doesn't appear to have been tampered significantly in the last 17 years.
Last time I used functioning turrets was in Privateer in 2006.

### PR DESCRIPTION
**Pull request by royfalk**
closes #1525 

**Code Changes:**
- [ ] Have the PR Validation Tests been run? see tests below

**Tests conducted:**
- Play-tested with Vigilance and H496. 
- Did not the standard tests yet. 

**Issues:**
- Open #1528 and #1529 for additional issues identified.

### CODE REVIEW

File: libraries/gfx_generic/cockpit_generic.cpp [hunk 1]
```diff
@@ -138,15 +137,16 @@ void Cockpit::Init(const char *file, bool isDisabled) {
...
+// A bad function name. 
+// This function potentially returns the current subunit, so its target can be extracted.
+// See star_system.cpp
 Unit *Cockpit::GetSaveParent() {
-    Unit *un = parentturret.GetUnit();
-    if (!un) {
-        un = parent.GetUnit();
-    }
-    return un;
+    return current_unit;
```
Comment (BenjamenMeyer) [inline libraries/gfx_generic/cockpit_generic.cpp:144]: should this be:
```
if (current_unit != nullptr) {
    return current_unit;
}
return parent_unit:
```
Or do we have some kind of guarantee that the `current_unit` is always properly set?

File: engine/src/gfx/cockpit.cpp [hunk 2]
```diff
@@ -1105,12 +1104,72 @@ void MapKey(const KBData &, KBSTATE k) {
...
+    }
+
+    VS_LOG(debug, (boost::format("GameCockpit::NextTurret - turrets = %1%") % number_of_turrets));
+    if(number_of_turrets == 0) {
+        return;
+    }
+
+    current_view++;
+    VS_LOG(debug, (boost::format("GameCockpit::NextTurret - current_view = %1%") % current_view));
+    if(current_view == number_of_turrets) {
```
Comment (BenjamenMeyer) [inline engine/src/gfx/cockpit.cpp:1132]: this would be better as `>=` to protect against increments that go too far

**Comment by royfalk** [comment]
I'll implement the suggestions in #1541.
