### PR TITLE
Detect whether on Linux or macOS using `uname` -- 0.9.x, SDL3 variant

### LINKED ISSUE #1443: We do not currently have real OS detection logic for Linux vs. macOS
**Describe the bug**
For bootstrapping purposes, among other things, we need to follow different code paths for Linux vs. macOS vs. Windows. We should auto-detect which one we are running on, but we have no such functionality today. Instead, we just read an environment variable, `MY_OS_NAME`.

**To Reproduce**
You can probably fool the system into thinking it's on macOS simply by setting `MY_OS_NAME` to "darwin" or something.

**Expected behavior**
The bootstrap script should call `uname` or similar to auto-detect which operating system we are truly running on.

**Please complete the following information):**
 - OS: [e.g. iOS] All
 - Software Versions [e.g. 22] N/A

**Additional context**
This same issue applied to the Build System Docker Images, as well; see https://github.com/vegastrike/build-system-docker-images/issues/89

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [x] This is a CI/build system change only

Issues:
- Addresses #1443 on 0.9.x_sdl3

Purpose:
- What is this pull request trying to do? Fix #1443 on 0.9.x_sdl3
- What release is this for? 0.9.x, SDL3 variant
- Is there a project or milestone we should apply this to? 0.9.x

### CODE REVIEW

File: script/bootstrap [hunk 1]
```diff
@@ -20,2066 +21,49 @@
...
-                      libboost-log-dev \
-                      libboost-regex-dev \
-                      libboost-program-options-dev \
-                      libxmu-dev \
-                      clang \
-                      lsb-release
-      ;;
+platform="$(uname | tr '[:upper:]' '[:lower:]')"
+
+case "$platform" in
```
Comment (royfalk) [inline script/bootstrap:38]: I like this. Now we're just missing bootstrap-on-windows.sh (bat?!).

File: script/bootstrap-on-linux.sh [hunk 2]
```diff
@@ -0,0 +1,2469 @@
...
+                          rpm-build \
+                          make \
+                          clang
+      ;;
+    "9.0")
+      dnf -y install dnf-plugins-core
+      dnf config-manager --set-enabled devel
+      dnf -y update
+      dnf -y install \
+                          git \
```
Comment (royfalk) [inline script/bootstrap-on-linux.sh]: This is a 2500 lines file. Most of what's here is packages.
I wonder if we can somehow shorten it or make it more maintainable. 
I can easily see us missing something on the next version of Linux mint.

**Review by royfalk — COMMENTED** [review]
My two cents:

File: script/bootstrap (hunk 1 above)
Comment (BenjamenMeyer) [reply script/bootstrap:38]: Windows uses a very different mechanism with the vcpkg.json tooling.

File: script/bootstrap-on-linux.sh (hunk 2 above)
Comment (BenjamenMeyer) [reply script/bootstrap-on-linux.sh]: I tried that at the beginning of things, and we've starting shortening it a little (see the 10/10.1 version).
I do agree it'd be nice if we could do a simple list for each type of installer, but different distros may end up with some slightly different requirements. Theoretically, Debian/Ubuntu/Mint should all have the same dependencies since Mint and Ubuntu more or less repackage Debian; but practically there are some variances, and often this happens between the releases too.

Perhaps we could compare and only split out when there is an actual differences between versions at a distro level; but that probably won't save much - RPM-based distros have the most differences IIRC.

File: script/bootstrap (hunk 1 above)
Comment (stephengtuggy) [reply script/bootstrap:38]: I think you're talking about bootstrap.ps1. 😄

Comment (BenjamenMeyer) [reply script/bootstrap:38]: @stephengtuggy yes, which only works in PowerShell. Sadly this is one area where Windows does things so differently that its not very compatible, and doesn't have a standard Unix shell utility by default.
