### PR TITLE
macOS support for 0.8.x release series

### LINKED ISSUE #78: Figure out MacOS compilation
Continuation of #42.

### LINKED ISSUE #533: Segmentation fault on MacOS 10.13.6 (macports)
This issue follows on from #78 and #524. @stephengtuggy and @nabaco asked me to copy over the debug information for the runtime issues I'm getting now that it actually builds on MacOS.

For reference, I installed the dependencies as follows:

```
sudo port install cmake expat jpeg libpng libvorbis boost gtk3 gtkglext libsdl mesa libGLU freeglut
```

## Segfault

```
./bin/vegastrike-engine -d../data
[2021-08-29 16:54:53.742580] [0x00007fffb2044380] [trace]   Registering codec ogg
[2021-08-29 16:54:53.743256] [0x00007fffb2044380] [trace]   .

Legacy Mode: FALSE
 In path /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/bin
Vega Strike
See http://www.gnu.org/copyleft/gpl.html for license details.

ARG #1 = -d../data
Using data dir specified on command line : ../data
GOT SUBDIR ARG =
Found data in ../data
Using /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data as data directory
Using .vegastrike as the home directory
Found MODDIR = /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/mods
USING HOMEDIR : /Users/dwales/.vegastrike As the home directory
CONFIGFILE - Found a config file in home directory, using : /Users/dwales/.vegastrike/vegastrike.config
DATADIR - No datadir specified in config file
Force galaxy to /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/universe/milky_way.xml
SIMULATION_ATOM: 0.01
['/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python39.zip', '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9', '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload']
['', '/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/modules/builtin', '/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/modules/quests', '/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/modules/missions', '/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/modules/ai', '/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/modules', '/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/bases', '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python39.zip', '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9', '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload']
zsh: segmentation fault  ./bin/vegastrike-engine -d../data
```

## Apple debug info

```
Process:               vegastrike-engine [5703]
Path:                  /Users/USER/Documents/*/vegastrike-engine
Identifier:            vegastrike-engine
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        zsh [92744]
Responsible:           vegastrike-engine [5703]
User ID:               501

Date/Time:             2021-08-29 16:58:15.171 +1000
OS Version:            Mac OS X 10.13.6 (17G6030)
Report Version:        12
Anonymous UUID:        F7AF7FD7-38D7-4F0F-FC40-D33697320272

Sleep/Wake UUID:       D66C618D-1419-469D-89A3-28C51F9DA481

Time Awake Since Boot: 3800000 seconds
Time Since Wake:       96000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0:
--> 
    __TEXT                 000000010c4cb000-000000010ce5b000 [ 9792K] r-x/rwx SM=COW  !-� [/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/bin/vegastrike-engine]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                           	000000000000000000 0 + 0
1   vegastrike-engine             	0x000000010c8dc454 GFXCreateProgramNoCache(char const*, char const*, char const*) + 3156 (gl_program.cpp:269)
2   vegastrike-engine             	0x000000010c8db5d4 GFXCreateProgram(char const*, char const*, char const*) + 564 (gl_program.cpp:353)
3   vegastrike-engine             	0x000000010c8ded3a getDefaultProgram() + 138 (gl_program.cpp:415)
4   vegastrike-engine             	0x000000010c8df439 GFXDefaultShaderSupported() + 9 (gl_program.cpp:553)
5   vegastrike-engine             	0x000000010c8e6028 init_opengl_extensions() + 5544 (gl_init.cpp:493)
6   vegastrike-engine             	0x000000010c8e783c GFXInit(int, char**) + 1612 (gl_init.cpp:620)
7   vegastrike-engine             	0x000000010c56dbae Universe::Universe(int, char**, char const*) + 126
8   vegastrike-engine             	0x000000010c905b9c SDL_main + 3948 (main.cpp:447)
9   vegastrike-engine             	0x000000010cd5832f -[SDLMain applicationDidFinishLaunching:] + 49
10  com.apple.CoreFoundation      	0x00007fff516e020c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
11  com.apple.CoreFoundation      	0x00007fff516e00da _CFXRegistrationPost + 458
12  com.apple.CoreFoundation      	0x00007fff516dfe11 ___CFXNotificationPost_block_invoke + 225
13  com.apple.CoreFoundation      	0x00007fff5169dbf0 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1664
14  com.apple.CoreFoundation      	0x00007fff5169cd27 _CFXNotificationPost + 599
15  com.apple.Foundation          	0x00007fff537ad817 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
16  com.apple.AppKit              	0x00007fff4ed97206 -[NSApplication _postDidFinishNotification] + 313
17  com.apple.AppKit              	0x00007fff4ed96e4f -[NSApplication _sendFinishLaunchingNotification] + 220
18  com.apple.AppKit              	0x00007fff4ec69ab3 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 562
19  com.apple.AppKit              	0x00007fff4ec696e9 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 690
20  com.apple.Foundation          	0x00007fff537f0664 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 287
21  com.apple.Foundation          	0x00007fff537f04e2 _NSAppleEventManagerGenericHandler + 102
22  com.apple.AE                  	0x00007fff527c8f08 aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 1788
23  com.apple.AE                  	0x00007fff527c87af dispatchEventAndSendReply(AEDesc const*, AEDesc*) + 41
24  com.apple.AE                  	0x00007fff527c869d aeProcessAppleEvent + 383
25  com.apple.HIToolbox           	0x00007fff509c44a0 AEProcessAppleEvent + 55
26  com.apple.AppKit              	0x00007fff4ec64d32 _DPSNextEvent + 2788
27  com.apple.AppKit              	0x00007fff4f3fae34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
28  com.apple.AppKit              	0x00007fff4ec59885 -[NSApplication run] + 764
29  vegastrike-engine             	0x000000010cd58961 main + 1321
30  libdyld.dylib                 	0x00007fff79600015 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff7975128a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7991820e _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff79917be9 start_wqthread + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff7975128a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7991820e _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff79917be9 start_wqthread + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff7975128a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7991820e _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff79917be9 start_wqthread + 13

Thread 4:: Dispatch queue: com.apple.Xplugin.CGEventPort
0   libsystem_kernel.dylib        	0x00007fff7974720a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff79746724 mach_msg + 60
2   com.apple.SkyLight            	0x00007fff733c2c51 CGSSnarfAndDispatchDatagrams + 168
3   com.apple.SkyLight            	0x00007fff73454b93 SLSGetNextEventRecordInternal + 81
4   com.apple.SkyLight            	0x00007fff734cd7dc SLEventCreateNextEvent + 44
5   libXplugin.1.dylib            	0x00007fff773a2c12 ___xp_init_service_cg_event_port_block_invoke + 104
6   libdispatch.dylib             	0x00007fff795c6db8 _dispatch_client_callout + 8
7   libdispatch.dylib             	0x00007fff795d9e81 _dispatch_continuation_pop + 472
8   libdispatch.dylib             	0x00007fff795c9081 _dispatch_source_invoke + 620
9   libdispatch.dylib             	0x00007fff795db07a _dispatch_queue_serial_drain + 222
10  libdispatch.dylib             	0x00007fff795ce166 _dispatch_queue_invoke + 373
11  libdispatch.dylib             	0x00007fff795dbf0d _dispatch_root_queue_drain_deferred_wlh + 332
12  libdispatch.dylib             	0x00007fff795dfd21 _dispatch_workloop_worker_thread + 880
13  libsystem_pthread.dylib       	0x00007fff79917fd2 _pthread_wqthread + 980
14  libsystem_pthread.dylib       	0x00007fff79917be9 start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff7975128a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7991820e _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff79917be9 start_wqthread + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff7975128a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7991820e _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff79917be9 start_wqthread + 13

Thread 7:
0   libsystem_kernel.dylib        	0x00007fff7975128a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7991820e _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff79917be9 start_wqthread + 13

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff7974725e semaphore_timedwait_trap + 10
1   libdispatch.dylib             	0x00007fff795d694f _dispatch_sema4_timedwait + 72
2   libdispatch.dylib             	0x00007fff795ce94e _dispatch_semaphore_wait_slow + 58
3   libdispatch.dylib             	0x00007fff795c9e53 _dispatch_worker_thread + 251
4   libsystem_pthread.dylib       	0x00007fff79918661 _pthread_body + 340
5   libsystem_pthread.dylib       	0x00007fff7991850d _pthread_start + 377
6   libsystem_pthread.dylib       	0x00007fff79917bf9 thread_start + 13

Thread 9:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff7974720a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff79746724 mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff5112387a HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned int, unsigned int, mach_msg_header_t*, bool, unsigned int) + 124
3   com.apple.audio.CoreAudio     	0x00007fff511237ed HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 45
4   com.apple.audio.CoreAudio     	0x00007fff51120859 HALC_ProxyIOContext::IOWorkLoop() + 977
5   com.apple.audio.CoreAudio     	0x00007fff511202bc HALC_ProxyIOContext::IOThreadEntry(void*) + 128
6   com.apple.audio.CoreAudio     	0x00007fff5111fffe HALB_IOThread::Entry(void*) + 72
7   libsystem_pthread.dylib       	0x00007fff79918661 _pthread_body + 340
8   libsystem_pthread.dylib       	0x00007fff7991850d _pthread_start + 377
9   libsystem_pthread.dylib       	0x00007fff79917bf9 thread_start + 13

Thread 10:
0   libsystem_kernel.dylib        	0x00007fff79747246 semaphore_wait_trap + 10
1   libdispatch.dylib             	0x00007fff795d6893 _dispatch_sema4_wait + 16
2   libdispatch.dylib             	0x00007fff795ce979 _dispatch_semaphore_wait_slow + 101
3   libopenal.1.dylib             	0x000000010e43816c EventThread(ALCcontext*) + 114
4   libopenal.1.dylib             	0x000000010e4388e4 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, int (*)(ALCcontext*), ALCcontext*> >(void*) + 44
5   libsystem_pthread.dylib       	0x00007fff79918661 _pthread_body + 340
6   libsystem_pthread.dylib       	0x00007fff7991850d _pthread_start + 377
7   libsystem_pthread.dylib       	0x00007fff79917bf9 thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000001  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000086170
  rdi: 0x0000000000008b31  rsi: 0x000000010f3b3a00  rbp: 0x00007ffee372f400  rsp: 0x00007ffee372e9a8
   r8: 0x000000000000003e   r9: 0x0000000000000000  r10: 0x000007fc2cbd76b0  r11: 0x000000000000003f
  r12: 0x00007ffee372eb20  r13: 0x00007ffee372f481  r14: 0x0000000000000001  r15: 0x000000010d7474c8
  rip: 0x0000000000000000  rfl: 0x0000000000000246  cr2: 0x000000010fc62000
  
Logical CPU:     0
Error Code:      0x020000b8
Trap Number:     133


Binary Images:
       0x10c4cb000 -        0x10ce5aff7 +vegastrike-engine (0) <D75B06B8-8AEB-31C2-89BF-FF9C1A16FEFE> /Users/USER/Documents/*/vegastrike-engine
       0x10dbb1000 -        0x10ddb2ff7 +org.python.python (3.9.6, [c] 2001-2019 Python Software Foundation. - 3.9.6) <8EBAE1AF-80B1-314B-B8F0-72D0E78494F9> /opt/local/Library/Frameworks/Python.framework/Versions/3.9/Python
       0x10df00000 -        0x10df01fff +libXdamage.1.dylib (0) <0B7F9941-738D-3964-AD55-9A542C20A28A> /opt/local/lib/libXdamage.1.dylib
       0x10df04000 -        0x10df29ff3 +libboost_python39-mt.dylib (0) <0B5FF608-AA91-3D70-BF71-62F5A5560A3E> /opt/local/libexec/*/libboost_python39-mt.dylib
       0x10df61000 -        0x10df61fff +libX11-xcb.1.dylib (0) <CE55158A-6F85-362C-B9AB-4F7E42AF84E6> /opt/local/lib/libX11-xcb.1.dylib
       0x10df65000 -        0x10dfdefff +libboost_log-mt.dylib (0) <6A52A139-AF75-3256-ACD9-F3FD1E542CDA> /opt/local/libexec/*/libboost_log-mt.dylib
       0x10e0b6000 -        0x10e0b9fff +libXxf86vm.1.dylib (0) <B6103B72-EA9E-39EA-80EF-567271445A85> /opt/local/lib/libXxf86vm.1.dylib
       0x10e0bc000 -        0x10e16cff3 +libboost_log_setup-mt.dylib (0) <7319394A-90FD-39E0-A079-E23532C528F3> /opt/local/libexec/*/libboost_log_setup-mt.dylib
       0x10e28f000 -        0x10e28ffff +libboost_date_time-mt.dylib (0) <8BE3B203-DAA7-3742-A6D7-D4809B8569C7> /opt/local/libexec/*/libboost_date_time-mt.dylib
       0x10e294000 -        0x10e294fff +libboost_system-mt.dylib (0) <87B3544D-ED1B-3029-ADC4-6A9159EC1E42> /opt/local/libexec/*/libboost_system-mt.dylib
       0x10e299000 -        0x10e2adff7 +libboost_filesystem-mt.dylib (0) <B950C770-84D7-3292-8712-92F27B58E44B> /opt/local/libexec/*/libboost_filesystem-mt.dylib
       0x10e2c1000 -        0x10e2ccffb +libboost_thread-mt.dylib (0) <42EFC730-7F87-30C0-B889-E29BF6D25C89> /opt/local/libexec/*/libboost_thread-mt.dylib
       0x10e2e2000 -        0x10e2e6ff3 +libboost_chrono-mt.dylib (0) <E100DE86-6EDF-308F-A69E-D58E685F9187> /opt/local/libexec/*/libboost_chrono-mt.dylib
       0x10e2ee000 -        0x10e2efff3 +libboost_atomic-mt.dylib (0) <5DB5226A-CE9B-3629-A577-C93479C4308E> /opt/local/libexec/*/libboost_atomic-mt.dylib
       0x10e2fb000 -        0x10e2fefff +libXfixes.3.dylib (0) <AA4BD5EC-422D-3426-A7E6-17BDB4532C8A> /opt/local/lib/libXfixes.3.dylib
       0x10e302000 -        0x10e346ff7 +libboost_regex-mt.dylib (0) <4B3DA9DA-8273-3ED3-97EA-D3D5E26DB4D1> /opt/local/libexec/*/libboost_regex-mt.dylib
       0x10e36c000 -        0x10e36dfff +libXau.6.dylib (0) <800D5456-D471-34E3-BB1E-F73D49C84CB7> /opt/local/lib/libXau.6.dylib
       0x10e370000 -        0x10e398fff +libglut.3.dylib (0) <3B487359-0F57-34AF-8E9A-176492622D98> /opt/local/lib/libglut.3.dylib
       0x10e427000 -        0x10e4b6fff +libopenal.1.dylib (0) <C4C94CD2-CE3E-36C0-A94E-55263FDC477B> /opt/local/lib/libopenal.1.dylib
       0x10e55d000 -        0x10e5a8ff7 +libSDL-1.2.0.dylib (0) <5213EF5D-1F45-3766-9BF7-C732F700CC98> /opt/local/lib/libSDL-1.2.0.dylib
       0x10e5c5000 -        0x10e5c8ff7 +libXdmcp.6.dylib (0) <FA25C972-7F2C-3975-88EE-C8D6AE0FAFB8> /opt/local/lib/libXdmcp.6.dylib
       0x10e5cb000 -        0x10e5edff7 +libvorbis.0.dylib (0) <82E7A48D-0776-3C17-B621-F620513EBCB7> /opt/local/lib/libvorbis.0.dylib
       0x10e5fc000 -        0x10e601fff +libvorbisfile.3.dylib (0) <C10D431E-8BB5-383A-8129-FB830234B6CB> /opt/local/lib/libvorbisfile.3.dylib
       0x10e60a000 -        0x10e60effb +libogg.0.dylib (0) <6C8F76CE-66CA-355C-A089-A6BC66D53E12> /opt/local/lib/libogg.0.dylib
       0x10e618000 -        0x10e693ffb +libjpeg.8.dylib (0) <48377147-BCC7-3CCE-95CA-5276071EB7D9> /opt/local/lib/libjpeg.8.dylib
       0x10e6b0000 -        0x10e6d3ffb +libpng16.16.dylib (0) <243C73AB-C942-3B3D-9F27-5AE60B09BE9F> /opt/local/lib/libpng16.16.dylib
       0x10e6de000 -        0x10e6eeff3 +libz.1.dylib (0) <ACB7269B-A127-30F2-8EE4-1F6E0B286AF1> /opt/local/lib/libz.1.dylib
       0x10e6f5000 -        0x10e70ffff +libexpat.1.dylib (0) <094C0679-7A62-36A8-94C7-DB2D5BB52A24> /opt/local/lib/libexpat.1.dylib
       0x10e719000 -        0x10e721ff7 +libintl.8.dylib (0) <A2F6BAEE-80BC-3FCF-AB28-FB9B93F5AD1B> /opt/local/lib/libintl.8.dylib
       0x10e72c000 -        0x10e820ff3 +libiconv.2.dylib (0) <23583374-BE1C-314C-B1C7-3DD94E1D394B> /opt/local/lib/libiconv.2.dylib
       0x10e82e000 -        0x10e9b9ff3 +libicui18n.67.dylib (0) <E7DBCE9F-1D4F-3B59-A563-3F5E4A8A30D1> /opt/local/lib/libicui18n.67.dylib
       0x10eac9000 -        0x10ebe9fff +libicuuc.67.dylib (0) <00A1EEE3-A31C-3D4B-A51C-A161EE11105B> /opt/local/lib/libicuuc.67.dylib
       0x10ec61000 -        0x10f089ff3 +libGL.1.dylib (0) <5F756C01-57B4-31B5-A2D0-3F48F4B84F25> /opt/local/lib/libGL.1.dylib
       0x10f1f7000 -        0x10f2e5ff7 +libX11.6.dylib (0) <B3018BE9-59A8-386C-A483-C8A343A46E6B> /opt/local/lib/libX11.6.dylib
       0x10f309000 -        0x10f30ffff +libXrandr.2.dylib (0) <AB6862B0-0703-3C43-A9A5-6D0594E74AA0> /opt/local/lib/libXrandr.2.dylib
       0x10f313000 -        0x10f31dfff +libXi.6.dylib (0) <A55C349B-032B-368E-BE7C-3CFB1F85268B> /opt/local/lib/libXi.6.dylib
       0x10f321000 -        0x10f343ff3 +libglapi.0.dylib (0) <1FC05E87-5132-34BE-A4DB-1171DB420071> /opt/local/lib/libglapi.0.dylib
       0x10f35c000 -        0x10f366ff3 +libXext.6.dylib (0) <46813B74-9EF2-355E-A258-B989E49A1276> /opt/local/lib/libXext.6.dylib
       0x10f36c000 -        0x10f37fff3 +libxcb.1.dylib (0) <9196418A-AB7A-3BC7-A43F-6D79773DB5ED> /opt/local/lib/libxcb.1.dylib
       0x10f390000 -        0x10f398fff +libxcb-glx.0.dylib (0) <84A27C14-2991-31B4-8D42-A81B90971BFF> /opt/local/lib/libxcb-glx.0.dylib
       0x10f3a8000 -        0x10f3aefff +libXrender.1.dylib (0) <C2E7FC59-B5BA-38AE-B267-C46462278A32> /opt/local/lib/libXrender.1.dylib
       0x110240000 -        0x110244ffb  com.apple.audio.AppleHDAHALPlugIn (281.52 - 281.52) <23C7DDE6-A44B-3BE4-B47C-EB3045B267D9> /System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn
       0x11024f000 -        0x110299acf  dyld (551.5) <30B355CB-35BA-3112-AA76-4E46CD45F699> /usr/lib/dyld
       0x1102ed000 -        0x111e02fff +libicudata.67.dylib (0) <AB92F086-9D87-3A72-B4FD-950F2B45B312> /opt/local/lib/libicudata.67.dylib
       0x115739000 -        0x1158e1ff7  com.apple.audio.units.Components (1.14 - 1.14) <1E04BB32-1550-3851-8CD1-4A588BFE5D46> /System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio
       0x1179b0000 -        0x117ef7fff  com.apple.driver.AppleIntelHD5000GraphicsGLDriver (10.36.23 - 10.3.6) <49BA7C3C-F0BC-3C65-9CDC-4A5BAF50D663> /System/Library/Extensions/AppleIntelHD5000GraphicsGLDriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsGLDriver
    0x7fff4b558000 -     0x7fff4b5ddff7  com.apple.driver.AppleIntelHD5000GraphicsMTLDriver (10.36.23 - 10.3.6) <D60F478D-5293-3DCD-A768-F851050562DE> /System/Library/Extensions/AppleIntelHD5000GraphicsMTLDriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsMTLDriver
    0x7fff4dbbd000 -     0x7fff4dbbdfff  com.apple.Accelerate (1.11 - Accelerate 1.11) <8632A9C5-19EA-3FD7-A44D-80765CC9C540> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff4dbbe000 -     0x7fff4dbd4fef  libCGInterfaces.dylib (417.2) <E08ADB62-DF87-3BC8-81C6-60438991D4E1> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fff4dbd5000 -     0x7fff4e0d3fc3  com.apple.vImage (8.1 - ???) <A243A7EF-0C8E-3A9A-AA38-44AFD7507F00> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff4e0d4000 -     0x7fff4e22efe3  libBLAS.dylib (1211.50.2) <62C659EB-3E32-3B5F-83BF-79F5DF30D5CE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff4e22f000 -     0x7fff4e25dfef  libBNNS.dylib (38.1) <7BAEFDCA-3227-3E07-80D8-59B6370B89C6> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fff4e25e000 -     0x7fff4e61dff7  libLAPACK.dylib (1211.50.2) <40ADBA5F-8B2D-30AC-A7AD-7B17C37EE52D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff4e61e000 -     0x7fff4e633ff7  libLinearAlgebra.dylib (1211.50.2) <E8E0B7FD-A0B7-31E5-AF01-81781F71EBBE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fff4e634000 -     0x7fff4e639ff3  libQuadrature.dylib (3) <3D6BF66A-55B2-3692-BAC7-DEB0C676ED29> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fff4e63a000 -     0x7fff4e6bafff  libSparse.dylib (79.50.2) <0DC25CDD-F8C1-3D6E-B472-8B060708424F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
    0x7fff4e6bb000 -     0x7fff4e6cefff  libSparseBLAS.dylib (1211.50.2) <722573CC-31CC-34B2-9032-E4F652A9CCFE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fff4e6cf000 -     0x7fff4e87cfc3  libvDSP.dylib (622.50.5) <40690941-CF89-3F90-A0AC-A4D200744A5D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fff4e87d000 -     0x7fff4e92efff  libvMisc.dylib (622.50.5) <BA2532DF-2D68-3DD0-9B59-D434BF702AA4> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff4e92f000 -     0x7fff4e92ffff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <54FF3B43-E66C-3F36-B34B-A2B3B0A36502> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff4ec23000 -     0x7fff4fa81fff  com.apple.AppKit (6.9 - 1561.60.100) <869D3CF3-E410-34A1-AA49-EF479DE941A1> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff4fad3000 -     0x7fff4fad3fff  com.apple.ApplicationServices (48 - 50) <3E227FC4-415F-3575-8C9C-8648301782C0> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff4fad4000 -     0x7fff4fb3afff  com.apple.ApplicationServices.ATS (377 - 445.5) <703CE7E4-426A-35C0-A229-F140F30F5340> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fff4fbd3000 -     0x7fff4fcf5fff  libFontParser.dylib (222.1.7) <9C4CEFB4-0F08-3B60-BD50-0120A37F6EA2> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
    0x7fff4fcf6000 -     0x7fff4fd40ff7  libFontRegistry.dylib (221.5) <8F68EA59-C8EE-3FA3-BD19-0F1A58441440> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fff4fde5000 -     0x7fff4fe18ff7  libTrueTypeScaler.dylib (222.1.7) <E401BD38-5F0E-382F-B4CB-AC6063871C0F> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libTrueTypeScaler.dylib
    0x7fff4fe82000 -     0x7fff4fe86ff3  com.apple.ColorSyncLegacy (4.13.0 - 1) <A5FB2694-1559-34A8-A3D3-2029F68A63CA> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
    0x7fff4ff26000 -     0x7fff4ff78ffb  com.apple.HIServices (1.22 - 624.1) <66FD9ED2-9630-313C-86AE-4C2FBCB3F351> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fff4ff79000 -     0x7fff4ff87fff  com.apple.LangAnalysis (1.7.0 - 1.7.0) <B65FF7E6-E9B5-34D8-8CA7-63D415A8A9A6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fff4ff88000 -     0x7fff4ffd4fff  com.apple.print.framework.PrintCore (13.4 - 503.2) <B90C67C1-0292-3CEC-885D-F1882CD104BE> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fff4ffd5000 -     0x7fff5000ffff  com.apple.QD (3.12 - 404.2) <38B20AFF-9D54-3B52-A6DC-C0D71380AA5F> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fff50010000 -     0x7fff5001cfff  com.apple.speech.synthesis.framework (7.8.1 - 7.8.1) <A08DE016-C8F2-3B0E-BD34-15959D13DBF0> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fff5001d000 -     0x7fff502abff7  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <E0B8B5D8-80A0-308B-ABD6-F8612102B5D8> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff502ad000 -     0x7fff502adfff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <ABF8778E-4F9D-305E-A528-DE406A1A2B68> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff505d0000 -     0x7fff5096bff7  com.apple.CFNetwork (902.3.1 - 902.3.1) <4C012538-BB8A-32F3-AACA-011092BEFAB1> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff50980000 -     0x7fff50980fff  com.apple.Carbon (158 - 158) <F8B370D9-2103-3276-821D-ACC756167F86> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff50981000 -     0x7fff50984ffb  com.apple.CommonPanels (1.2.6 - 98) <2391761C-5CAA-3F68-86B7-50B37927B104> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fff50985000 -     0x7fff50c8afff  com.apple.HIToolbox (2.1.1 - 911.10) <BF7F9C0E-C732-3FB2-9BBC-362888BDA57B> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff50c8b000 -     0x7fff50c8effb  com.apple.help (1.3.8 - 66) <DEBADFA8-C189-3195-B0D6-A1F2DE95882A> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fff50c8f000 -     0x7fff50c94fff  com.apple.ImageCapture (9.0 - 9.0) <23B4916F-3B43-3DFF-B956-FC390EECA284> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fff50c95000 -     0x7fff50d2affb  com.apple.ink.framework (10.9 - 221) <5206C8B0-22DA-36C9-998E-846EDB626D5B> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fff50d2b000 -     0x7fff50d45ff7  com.apple.openscripting (1.7 - 174) <1B2A1F9E-5534-3D61-83CA-9199B39E8708> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fff50d66000 -     0x7fff50d67fff  com.apple.print.framework.Print (12 - 267) <3682ABFB-2561-3419-847D-02C247F4800D> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fff50d68000 -     0x7fff50d6aff7  com.apple.securityhi (9.0 - 55006) <C1406B8D-7D05-3959-808F-9C82189CF57F> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fff50d6b000 -     0x7fff50d71fff  com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <2ED8643D-B0C3-3F17-82A2-BBF13E6CBABC> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fff50e92000 -     0x7fff50e92fff  com.apple.Cocoa (6.11 - 22) <8C1B3F7A-889A-3D71-A58C-C672665F9E78> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff50ea0000 -     0x7fff50f59fff  com.apple.ColorSync (4.13.0 - 3325) <D283C285-447D-3258-A7E4-59532123B8FF> /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fff510e6000 -     0x7fff51179ff7  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <EB35D3EC-56EA-33E6-98DC-BDC3A5FA8ACE> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff511e0000 -     0x7fff51209ffb  com.apple.CoreBluetooth (1.0 - 1) <E1335074-9D07-370E-8440-61C4874BAC56> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff5120a000 -     0x7fff51560fef  com.apple.CoreData (120 - 851) <A2B59780-FB16-36A3-8EE0-E0EF072454E0> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff51561000 -     0x7fff51644fff  com.apple.CoreDisplay (99.14 - 99.14) <A1B91ADD-828D-33A0-8A92-CC3F83DF89D0> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff51645000 -     0x7fff51ae6fe7  com.apple.CoreFoundation (6.9 - 1454.95) <2FC52F3C-CCEA-3EDA-8337-1FE84E755FF7> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff51ae8000 -     0x7fff520f8fef  com.apple.CoreGraphics (2.0 - 1161.21.2) <B3ECE8F4-92B5-3E04-A30D-72540D3B93CB> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff520fa000 -     0x7fff523e9fff  com.apple.CoreImage (13.0.0 - 579.5) <AAE2DFD0-9B0A-3D56-8A3E-C460BAF70394> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff527be000 -     0x7fff527befff  com.apple.CoreServices (822.37 - 822.37) <19C9118E-08B7-3FF7-B252-5C9571C7882C> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff527bf000 -     0x7fff52833ffb  com.apple.AE (735.2 - 735.2) <690A6F47-1306-371F-B257-783D8F83EA9E> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff52834000 -     0x7fff52b0bfff  com.apple.CoreServices.CarbonCore (1178.4.1 - 1178.4.1) <009E1ABC-A66B-3355-9E6C-0D4E9B7BEA4C> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff52b0c000 -     0x7fff52b40fff  com.apple.DictionaryServices (1.2 - 284.2) <6505B075-41C3-3C62-A4C3-85CE3F6825CD> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff52b41000 -     0x7fff52b49ffb  com.apple.CoreServices.FSEvents (1239.50.1 - 1239.50.1) <3637CEC7-DF0E-320E-9634-44A442925C65> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fff52b4a000 -     0x7fff52d08ff7  com.apple.LaunchServices (822.37 - 822.37) <6AA93307-220A-3417-BBC2-FE1C0DE0B652> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff52d09000 -     0x7fff52db9fff  com.apple.Metadata (10.7.0 - 1191.7) <3DD530A7-E104-3469-98BB-20449834B2FE> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff52dba000 -     0x7fff52e1afff  com.apple.CoreServices.OSServices (822.37 - 822.37) <4AD2FC98-C6CB-392A-A22F-196A723D7FAE> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff52e1b000 -     0x7fff52e89fff  com.apple.SearchKit (1.4.0 - 1.4.0) <3662545A-B1CF-3079-BDCD-C83855CEFEEE> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff52e8a000 -     0x7fff52eaeffb  com.apple.coreservices.SharedFileList (71.21 - 71.21) <1B5228EF-D869-3A50-A373-7F4B0289FADD> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fff5314f000 -     0x7fff5329ffff  com.apple.CoreText (352.0 - 578.22) <6129F39D-284D-3BBF-8999-7854AB61C01C> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff532a0000 -     0x7fff532dafff  com.apple.CoreVideo (1.8 - 0.0) <86CCC036-51BB-3DD1-9601-D93798BCCD0F> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff532db000 -     0x7fff53366ff3  com.apple.framework.CoreWLAN (13.0 - 1350.2) <829B4EAC-5AC9-353C-8D0F-565578EF2A6F> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff535e1000 -     0x7fff535e6fff  com.apple.DiskArbitration (2.7 - 2.7) <2F628584-8177-3894-92CE-9CA6089B61C6> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff537a7000 -     0x7fff53b6dff3  com.apple.Foundation (6.9 - 1454.95) <0A759716-AD1C-3409-A8FD-D6C615FADB7F> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff53bde000 -     0x7fff53c0eff3  com.apple.GSS (4.0 - 2.0) <62F1A2A7-EBDB-3CAB-8306-4DA9EFA70E81> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff53d20000 -     0x7fff53e24ffb  com.apple.Bluetooth (6.0.7 - 6.0.7f12) <D453376E-5CE7-39FA-A28E-4C8ABFCF31E1> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff53e84000 -     0x7fff53f1ffff  com.apple.framework.IOKit (2.0.2 - 1445.71.5) <59191D07-0C8E-3823-A124-CE46F1A35935> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff53f21000 -     0x7fff53f28fff  com.apple.IOSurface (211.15 - 211.15) <9FD406F1-6BF2-35B0-8339-DF83A1A661EB> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff53f7f000 -     0x7fff540f9ff7  com.apple.ImageIO.framework (3.3.0 - 1739.3) <7C579D3F-AE0B-31C9-8F80-67F2290B8DE0> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff540fa000 -     0x7fff540feffb  libGIF.dylib (1739.3) <7AA44C9D-48E8-3090-B044-61FE6F0AEF38> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fff540ff000 -     0x7fff541e6fef  libJP2.dylib (1739.3) <AEBF7260-0C10-30C0-8F0F-8B347DEE78B3> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fff541e7000 -     0x7fff5420aff7  libJPEG.dylib (1739.3) <D8C966AD-A00C-3E8B-A7ED-D7CC7ECB3224> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fff544e6000 -     0x7fff5450cfeb  libPng.dylib (1739.3) <1737F680-99D1-3F03-BFA5-5CDA30EB880A> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fff5450d000 -     0x7fff5450fffb  libRadiance.dylib (1739.3) <21746434-FCC7-36DE-9331-11277DF66AA8> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fff54510000 -     0x7fff5455efef  libTIFF.dylib (1739.3) <C4CB5C1D-20F2-3BD4-B0E6-629FDB3EF8E8> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fff55418000 -     0x7fff55431ff7  com.apple.Kerberos (3.0 - 1) <F86DCCDF-93C1-38B3-82C2-477C12E8EE6D> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff55e13000 -     0x7fff55e94fff  com.apple.Metal (125.30 - 125.30) <6B9EBDEE-C64C-3C1C-922A-0363B642C9BC> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff55eb1000 -     0x7fff55eccfff  com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) <AD754E8F-CA00-3878-9AF3-208C224A230B> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/Versions/A/MPSCore
    0x7fff55ecd000 -     0x7fff55f3cfef  com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <338B7779-E608-3D68-8A07-2ACC11299744> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/Versions/A/MPSImage
    0x7fff55f3d000 -     0x7fff55f61fff  com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <9CE072D7-853B-3939-9645-7EB951376B87> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
    0x7fff55f62000 -     0x7fff56049ff7  com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <0DE891AD-27E5-38FF-AEC8-4A95356C4357> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
    0x7fff5604a000 -     0x7fff5604aff7  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <2D2D261C-50B0-32F9-BF9A-5C01382BB528> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fff57049000 -     0x7fff57055ffb  com.apple.NetFS (6.0 - 4.0) <471DD96F-FA2E-3FE9-9746-2519A6780D1A> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fff59e3e000 -     0x7fff59e46fef  libcldcpuengine.dylib (2.8.7) <EF9A91AC-029C-300A-99E7-4952C15DA09F> /System/Library/Frameworks/OpenCL.framework/Versions/A/Libraries/libcldcpuengine.dylib
    0x7fff59e47000 -     0x7fff59ea1ff7  com.apple.opencl (2.8.24 - 2.8.24) <058114A8-6825-31D7-976E-0612B6A273E9> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fff59ea2000 -     0x7fff59ebeffb  com.apple.CFOpenDirectory (10.13 - 207.50.1) <29F55F7B-379F-3053-8FF3-5C6675A3DD4D> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff59ebf000 -     0x7fff59ecafff  com.apple.OpenDirectory (10.13 - 207.50.1) <F895547D-4915-353F-9C1E-E95172BA803B> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff5b049000 -     0x7fff5b04bfff  libCVMSPluginSupport.dylib (16.7.4) <F9270AE0-CC3B-3E3E-BA32-CC1068DD8F27> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fff5b04c000 -     0x7fff5b051ffb  libCoreFSCache.dylib (162.9) <DD9DD721-2957-3D05-B361-70AF9EBFB280> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fff5b052000 -     0x7fff5b056fff  libCoreVMClient.dylib (162.9) <4E4F3EA2-5B53-31A3-8256-54EFAA94E4D6> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fff5b057000 -     0x7fff5b060ff3  libGFXShared.dylib (16.7.4) <EB2BF8A0-E10D-35EA-8F46-B2E3C62C12A8> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fff5b061000 -     0x7fff5b06cfff  libGL.dylib (16.7.4) <2BB333D3-5C61-33DF-8545-06DF2D08B83D> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fff5b06d000 -     0x7fff5b0a8fe7  libGLImage.dylib (16.7.4) <4DA003CE-0B74-3FE4-808C-B2FBCE517EB4> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fff5b0a9000 -     0x7fff5b216ff3  libGLProgrammability.dylib (16.7.4) <ECC9D79B-C0B1-33F9-A9BB-097EF12D9E13> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib
    0x7fff5b217000 -     0x7fff5b255ffb  libGLU.dylib (16.7.4) <BCB09CD8-EB0E-38FA-8B5A-9E29532EE364> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fff5bbcd000 -     0x7fff5bbdcff3  com.apple.opengl (16.7.4 - 16.7.4) <9BDE8FF9-5418-3C70-8D1C-09656884CE48> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff5bbdd000 -     0x7fff5bd74ff3  GLEngine (16.7.4) <E2EE1D9C-826E-3DA9-9DCA-2FF371CDE5BB> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine
    0x7fff5bd75000 -     0x7fff5bd9dffb  GLRendererFloat (16.7.4) <3B51AC1B-0A3C-30E5-80EB-F64EBB1B1F77> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLRendererFloat.bundle/GLRendererFloat
    0x7fff5ca2b000 -     0x7fff5cc77ff7  com.apple.QuartzCore (1.11 - 584.64.2) <37BA5F4F-6B51-3B33-85A6-13673CBF6F3B> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff5d4b0000 -     0x7fff5d7dbfff  com.apple.security (7.0 - 58286.70.13) <2AE4C057-B8D1-3DD0-A634-5C50C5146B49> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff5d7dc000 -     0x7fff5d868ff7  com.apple.securityfoundation (6.0 - 55185.50.5) <507A174F-35D6-3004-A22F-513CD4FD8579> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff5d89a000 -     0x7fff5d89effb  com.apple.xpc.ServiceManagement (1.0 - 1) <884CC665-5725-3C74-97E2-11D410DF0490> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff5dc43000 -     0x7fff5dcb3ff3  com.apple.SystemConfiguration (1.17 - 1.17) <CD4A4C66-7886-3323-A3B9-0C8952500856> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff60bb0000 -     0x7fff60c43fff  com.apple.APFS (1.0 - 1) <39C3577D-FBFF-337F-B9CD-7E73B68B5504> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fff6186f000 -     0x7fff61897fff  com.apple.framework.Apple80211 (13.0 - 1370.4) <0FE38EB2-0E2B-38E6-8F15-BE082A1A36E2> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fff61899000 -     0x7fff618a8fef  com.apple.AppleFSCompression (96.60.1 - 1.0) <A7C875C4-F5EE-3272-AFB6-57C9FD5352B3> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff619a7000 -     0x7fff619b2ff7  com.apple.AppleIDAuthSupport (1.0 - 1) <2FAF5567-CDB3-33EF-AB71-05D37F2248B7> /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/Versions/A/AppleIDAuthSupport
    0x7fff619ec000 -     0x7fff61a34ff3  com.apple.AppleJPEG (1.0 - 1) <8DD410CB-76A1-3F22-9A9F-0491FA0CEB4A> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fff61a6f000 -     0x7fff61a97fff  com.apple.applesauce (1.0 - ???) <CCA8B094-1BCE-3AE3-A0A7-D544C818DE36> /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce
    0x7fff61eea000 -     0x7fff62183ffb  com.apple.AuthKit (1.0 - 1) <6CA71A11-91C5-307C-B933-9FCDEDCB580A> /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit
    0x7fff622ba000 -     0x7fff622c1ff7  com.apple.coreservices.BackgroundTaskManagement (1.0 - 57.1) <51A41CA3-DB1D-3380-993E-99C54AEE518E> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
    0x7fff622c2000 -     0x7fff62349ff7  com.apple.backup.framework (1.9.6 - 1.9.6) <3C96FD26-C7F2-3F37-885A-5A71372FA8F4> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
    0x7fff63d03000 -     0x7fff63d0cff3  com.apple.CommonAuth (4.0 - 2.0) <FBBD852E-FFFE-396B-A343-2C5DB7A3D819> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff64820000 -     0x7fff64830ff7  com.apple.CoreEmoji (1.0 - 69.3) <A4357F5C-0C38-3A61-B456-D7321EB2CEE5> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fff64fc4000 -     0x7fff64fccff3  com.apple.CorePhoneNumbers (1.0 - 1) <A5D41251-9F38-3AB9-9DE7-F77023FAAA44> /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/Versions/A/CorePhoneNumbers
    0x7fff65157000 -     0x7fff65188ff3  com.apple.CoreServicesInternal (309.1 - 309.1) <4ECD14EA-A493-3B84-A32F-CF928474A405> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff65502000 -     0x7fff65593fff  com.apple.CoreSymbolication (9.3 - 64026.2) <A8D4315F-5DD5-3164-8672-ECDAF2766644> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff65616000 -     0x7fff6574bfff  com.apple.coreui (2.1 - 494.1) <B2C515C3-FCE8-3B28-A225-05AD917F509B> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff6574c000 -     0x7fff6587dfff  com.apple.CoreUtils (5.6 - 560.11) <1A02D6F0-8C65-3FAE-AD63-56477EDE4773> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff658d2000 -     0x7fff65936fff  com.apple.framework.CoreWiFi (13.0 - 1350.2) <CB841DAA-7777-38FE-9C96-C709EB6A0D90> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
    0x7fff65937000 -     0x7fff65947ff7  com.apple.CrashReporterSupport (10.13 - 1) <A909F468-0648-3F51-A77E-3F9ADBC9A941> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff659c6000 -     0x7fff659d5ff7  com.apple.framework.DFRFoundation (1.0 - 191.7) <3B8ED6F7-5DFF-34C3-BA90-DDB85679684C> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff659d8000 -     0x7fff659dcffb  com.apple.DSExternalDisplay (3.1 - 380) <901B7F6D-376A-3848-99D0-170C4D00F776> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fff65a5e000 -     0x7fff65ad4fff  com.apple.datadetectorscore (7.0 - 590.3) <B4706195-CBE6-320D-A0E1-A9D4BDF52791> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff65b22000 -     0x7fff65b62ff7  com.apple.DebugSymbols (181.0 - 181.0) <299A0238-ED78-3676-B131-274D972824AA> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff65b63000 -     0x7fff65c92fff  com.apple.desktopservices (1.12.5 - 1.12.5) <7739C9A5-64D9-31A5-899B-5FFA242AD70D> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff66aad000 -     0x7fff66edbfff  com.apple.vision.FaceCore (3.3.2 - 3.3.2) <B574FE33-4A41-3611-9738-388EBAF03E37> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fff68b37000 -     0x7fff68b37fff  libmetal_timestamp.dylib (802.4.8) <B428D084-681A-3A20-837D-6BCB3B2AE2A3> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/3802/Libraries/libmetal_timestamp.dylib
    0x7fff6a197000 -     0x7fff6a1a2ff7  libGPUSupportMercury.dylib (16.7.4) <A4D6F79C-1DFA-3E96-8F76-4882FBEDE9CF> /System/Library/PrivateFrameworks/GPUSupport.framework/Versions/A/Libraries/libGPUSupportMercury.dylib
    0x7fff6a1a3000 -     0x7fff6a1a8fff  com.apple.GPUWrangler (3.20.0 - 3.20.0) <52CF4100-EEC3-3557-8519-BA5A1FB37D90> /System/Library/PrivateFrameworks/GPUWrangler.framework/Versions/A/GPUWrangler
    0x7fff6af1e000 -     0x7fff6af2dfff  com.apple.GraphVisualizer (1.0 - 5) <B993B8A2-5700-3DFC-9EB7-4CCEE8F959F1> /System/Library/PrivateFrameworks/GraphVisualizer.framework/Versions/A/GraphVisualizer
    0x7fff6afb0000 -     0x7fff6b024fff  com.apple.Heimdal (4.0 - 2.0) <9F4D7008-944E-3A7C-8E58-A9F7D8497C32> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff6b934000 -     0x7fff6b93bff7  com.apple.IOAccelerator (378.26 - 378.26) <2274BE11-18DE-3B13-BCDB-C488C9BB19AD> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fff6b93f000 -     0x7fff6b956fff  com.apple.IOPresentment (1.0 - 35.1) <7C6332FF-6535-3064-B437-1E9F70671927> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fff6bd21000 -     0x7fff6bd47ffb  com.apple.IconServices (97.6 - 97.6) <A56D826D-20D2-34BE-AACC-A80CFCB4E915> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fff6bfcc000 -     0x7fff6bfdfff3  com.apple.security.KeychainCircle.KeychainCircle (1.0 - 1) <CCFECD89-2469-375C-86E2-892D1A7EA47B> /System/Library/PrivateFrameworks/KeychainCircle.framework/Versions/A/KeychainCircle
    0x7fff6bfe0000 -     0x7fff6c0d5ff7  com.apple.LanguageModeling (1.0 - 159.5.3) <7F0AC200-E3DD-39FB-8A95-00DD70B66A9F> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fff6c0d6000 -     0x7fff6c118fff  com.apple.Lexicon-framework (1.0 - 33.5) <DC94CF9E-1EB4-3C0E-B298-CA1190885276> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
    0x7fff6c11c000 -     0x7fff6c123ff7  com.apple.LinguisticData (1.0 - 238.3) <49A54649-1021-3DBD-99B8-1B2EDFFA5378> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
    0x7fff6ce35000 -     0x7fff6ce9eff7  com.apple.gpusw.MetalTools (1.0 - 1) <B4217182-B2AA-3AA3-80E8-F4C80B71BDDC> /System/Library/PrivateFrameworks/MetalTools.framework/Versions/A/MetalTools
    0x7fff6d02e000 -     0x7fff6d047fff  com.apple.MobileKeyBag (2.0 - 1.0) <BE1FFE6C-0F68-3AAE-820A-93CA0EA5F732> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fff6d0d3000 -     0x7fff6d0fdffb  com.apple.MultitouchSupport.framework (1614.1 - 1614.1) <A0709B43-FA9E-3617-8E7A-D68CDFAB2167> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fff6d364000 -     0x7fff6d36ffff  com.apple.NetAuth (6.2 - 6.2) <62A8E863-18C3-36E5-ABF5-B9614CA40374> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff6ec08000 -     0x7fff6ec18ffb  com.apple.PerformanceAnalysis (1.194 - 194) <8022ED1F-CE70-388E-B37B-6FB1E5F90CF2> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fff709d7000 -     0x7fff709f5fff  com.apple.ProtocolBuffer (1 - 260) <40704740-4A53-3010-A49B-08D1D69D1D5E> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fff70bd0000 -     0x7fff70bf3ffb  com.apple.RemoteViewServices (2.0 - 125) <592323D1-CB44-35F1-9921-4C2AB8D920A0> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fff72519000 -     0x7fff7262eff7  com.apple.Sharing (1050.22.3 - 1050.22.3) <BD9A4548-CAB5-3B44-8472-3973880BC9BC> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fff72659000 -     0x7fff7265aff7  com.apple.performance.SignpostNotification (1.2.6 - 2.6) <8F04800F-3570-3392-A24D-B229FF03F7F9> /System/Library/PrivateFrameworks/SignpostNotification.framework/Versions/A/SignpostNotification
    0x7fff733b7000 -     0x7fff73653fff  com.apple.SkyLight (1.600.0 - 312.103.11) <2E04D36B-F539-356A-BED5-781CD98C2C96> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff73e1c000 -     0x7fff73e29fff  com.apple.SpeechRecognitionCore (4.6.1 - 4.6.1) <87EE7AB5-6925-3D21-BE00-F155CB457699> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fff749cf000 -     0x7fff74a58fc7  com.apple.Symbolication (9.3 - 64033) <FAA17252-6378-34A4-BBBB-22DF54EC1626> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
    0x7fff74fc8000 -     0x7fff74fd0ff7  com.apple.TCC (1.0 - 1) <E1EB7272-FE6F-39AB-83CA-B2B5F2A88D9B> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff751dd000 -     0x7fff7529aff7  com.apple.TextureIO (3.7 - 3.7) <F8BAC954-405D-3CC3-AB7B-048C866EF980> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fff75344000 -     0x7fff75345fff  com.apple.TrustEvaluationAgent (2.0 - 31) <39F533B2-211E-3635-AF47-23F27749FF4A> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fff7534b000 -     0x7fff754fafff  com.apple.UIFoundation (1.0 - 547.5) <86A2FBA7-2709-3894-A3D5-A00C19BAC48D> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fff76c76000 -     0x7fff76c78ffb  com.apple.loginsupport (1.0 - 1) <D1232C1B-80EA-3DF8-9466-013695D0846E> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fff76ddf000 -     0x7fff76e12ff7  libclosured.dylib (551.5) <112BC241-6626-3848-8DD8-B34B5B6F7ABC> /usr/lib/closure/libclosured.dylib
    0x7fff76ecc000 -     0x7fff76f05ff7  libCRFSuite.dylib (41) <FE5EDB68-2593-3C2E-BBAF-1C52D206F296> /usr/lib/libCRFSuite.dylib
    0x7fff76f06000 -     0x7fff76f11fff  libChineseTokenizer.dylib (28) <53633C9B-A3A8-36F7-A53C-432D802F4BB8> /usr/lib/libChineseTokenizer.dylib
    0x7fff76fa3000 -     0x7fff76fa4ff3  libDiagnosticMessagesClient.dylib (104) <9712E980-76EE-3A89-AEA6-DF4BAF5C0574> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff76fdb000 -     0x7fff771a5ff3  libFosl_dynamic.dylib (17.8) <C58ED77A-4986-31C2-994C-34DDFB8106F0> /usr/lib/libFosl_dynamic.dylib
    0x7fff771dd000 -     0x7fff771ddfff  libOpenScriptingUtil.dylib (174) <610F0242-7CE5-3C86-951B-B646562694AF> /usr/lib/libOpenScriptingUtil.dylib
    0x7fff77314000 -     0x7fff77318ffb  libScreenReader.dylib (562.18.4) <E239923D-54C9-3BBF-852F-87C09DEF4091> /usr/lib/libScreenReader.dylib
    0x7fff77319000 -     0x7fff7731affb  libSystem.B.dylib (1252.50.4) <88203CF0-5028-3653-BD02-A5E6DD7F1B2D> /usr/lib/libSystem.B.dylib
    0x7fff773a0000 -     0x7fff773acff3  libXplugin.1.dylib (47) <99DCDCAD-F7C9-3183-BB09-CA577B087485> /usr/lib/libXplugin.1.dylib
    0x7fff773ad000 -     0x7fff773adfff  libapple_crypto.dylib (109.50.14) <48BA2E76-BF2F-3522-A54E-D7FB7EAF7A57> /usr/lib/libapple_crypto.dylib
    0x7fff773ae000 -     0x7fff773c4ff7  libapple_nghttp2.dylib (1.24) <01402BC4-4822-3676-9C80-50D83F816424> /usr/lib/libapple_nghttp2.dylib
    0x7fff773c5000 -     0x7fff773efff3  libarchive.2.dylib (54) <8FC28DD8-E315-3C3E-95FE-D1D2CBE49888> /usr/lib/libarchive.2.dylib
    0x7fff773f0000 -     0x7fff77471fdf  libate.dylib (1.13.1) <178ACDAD-DE7E-346C-A613-1CBF7929AC07> /usr/lib/libate.dylib
    0x7fff77475000 -     0x7fff77475ff3  libauto.dylib (187) <A05C7900-F8C7-3E75-8D3F-909B40C19717> /usr/lib/libauto.dylib
    0x7fff77476000 -     0x7fff7752eff3  libboringssl.dylib (109.50.14) <E6813F87-B5E4-3F7F-A725-E6A7F2BD02EC> /usr/lib/libboringssl.dylib
    0x7fff7752f000 -     0x7fff7753fff3  libbsm.0.dylib (39) <6BC96A72-AFBE-34FD-91B1-748A530D8AE6> /usr/lib/libbsm.0.dylib
    0x7fff77540000 -     0x7fff7754dffb  libbz2.1.0.dylib (38) <0A5086BB-4724-3C14-979D-5AD4F26B5B45> /usr/lib/libbz2.1.0.dylib
    0x7fff7754e000 -     0x7fff775a4fff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff775a5000 -     0x7fff775c9ff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff775cb000 -     0x7fff775dbfff  libcmph.dylib (6) <890DEC4C-4334-393C-8B56-7C8560BBED9D> /usr/lib/libcmph.dylib
    0x7fff775dc000 -     0x7fff775f3fcf  libcompression.dylib (47.60.2) <543F07BF-2F2F-37D5-9866-E84BF659885B> /usr/lib/libcompression.dylib
    0x7fff7789e000 -     0x7fff778b6ff7  libcoretls.dylib (155.50.1) <D350052E-DC4D-3185-ADBA-BA48EDCEE955> /usr/lib/libcoretls.dylib
    0x7fff778b7000 -     0x7fff778b8ff3  libcoretls_cfhelpers.dylib (155.50.1) <B297F5D8-F2FE-3566-A752-E9D998B9C039> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fff77a51000 -     0x7fff77be2fff  libcrypto.35.dylib (22.50.3) <6E609F99-59BC-3AEA-9DB3-FD360A2C50CC> /usr/lib/libcrypto.35.dylib
    0x7fff77d89000 -     0x7fff77ddfff3  libcups.2.dylib (462.2.5) <EA944DD1-0B60-32E9-8FB4-BE642D2E7352> /usr/lib/libcups.2.dylib
    0x7fff77f1f000 -     0x7fff77f1ffff  libenergytrace.dylib (16) <A92AB8B8-B986-3CE6-980D-D55090FEF387> /usr/lib/libenergytrace.dylib
    0x7fff77f56000 -     0x7fff77f5bff3  libheimdal-asn1.dylib (520.50.8) <6C10CD33-2920-340F-A98B-E1A465A40D03> /usr/lib/libheimdal-asn1.dylib
    0x7fff77f87000 -     0x7fff78078ff7  libiconv.2.dylib (51.50.1) <2FEC9707-3FAF-3828-A50D-8605086D060F> /usr/lib/libiconv.2.dylib
    0x7fff78079000 -     0x7fff782a0ffb  libicucore.A.dylib (59181.0.1) <2CE6205F-D375-3BF5-AA0A-3254BC4773D0> /usr/lib/libicucore.A.dylib
    0x7fff782ed000 -     0x7fff782eefff  liblangid.dylib (128) <39C39393-0D05-301D-93B2-F224FC4949AA> /usr/lib/liblangid.dylib
    0x7fff782ef000 -     0x7fff78308ffb  liblzma.5.dylib (10) <3D419A50-961F-37D2-8A01-3DC7AB7B8D18> /usr/lib/liblzma.5.dylib
    0x7fff78309000 -     0x7fff7831fff7  libmarisa.dylib (9) <D6D2D55D-1D2E-3442-B152-B18803C0ABB4> /usr/lib/libmarisa.dylib
    0x7fff783d0000 -     0x7fff785f8ff7  libmecabra.dylib (779.7.6) <F462F170-E872-3D09-B219-973D5E99C09F> /usr/lib/libmecabra.dylib
    0x7fff787d0000 -     0x7fff7894bfff  libnetwork.dylib (1229.70.2) <E185D902-AC7F-3044-87C0-AE2887C59CE7> /usr/lib/libnetwork.dylib
    0x7fff789d2000 -     0x7fff78dc07e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff78dd3000 -     0x7fff78dd7fff  libpam.2.dylib (22) <7B4D2CE2-1438-387A-9802-5CEEFBF26F86> /usr/lib/libpam.2.dylib
    0x7fff78dda000 -     0x7fff78e0efff  libpcap.A.dylib (79.20.1) <FA13918B-A247-3181-B256-9B852C7BA316> /usr/lib/libpcap.A.dylib
    0x7fff78e8d000 -     0x7fff78ea9ffb  libresolv.9.dylib (65) <E8F3415B-4472-3202-8901-41FD87981DB2> /usr/lib/libresolv.9.dylib
    0x7fff78efa000 -     0x7fff7908dff7  libsqlite3.dylib (274.8.1) <FCAD6A57-829E-3701-B16E-1833D620E0E8> /usr/lib/libsqlite3.dylib
    0x7fff79261000 -     0x7fff792c1ff3  libusrtcp.dylib (1229.70.2) <1E065228-D0E3-3808-9405-894056C6BEC0> /usr/lib/libusrtcp.dylib
    0x7fff792c2000 -     0x7fff792c5ffb  libutil.dylib (51.20.1) <216D18E5-0BAF-3EAF-A38E-F6AC37CBABD9> /usr/lib/libutil.dylib
    0x7fff792c6000 -     0x7fff792d3ff3  libxar.1.dylib (417.1) <351781D5-3CCF-320F-BB5A-4DFCC1CCD31D> /usr/lib/libxar.1.dylib
    0x7fff792d7000 -     0x7fff793befff  libxml2.2.dylib (31.13) <8C12B82A-66FD-330C-9BEA-AAC090C7076A> /usr/lib/libxml2.2.dylib
    0x7fff793bf000 -     0x7fff793e7fff  libxslt.1.dylib (15.12) <4A5E011D-8B29-3135-A52B-9A9070ABD752> /usr/lib/libxslt.1.dylib
    0x7fff793e8000 -     0x7fff793faffb  libz.1.dylib (70) <48C67CFC-940D-3857-8DAD-857774605352> /usr/lib/libz.1.dylib
    0x7fff79496000 -     0x7fff7949aff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff7949b000 -     0x7fff794a5ff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff794a6000 -     0x7fff794adfff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff794ae000 -     0x7fff794b7ffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff794b8000 -     0x7fff7953dffb  libcorecrypto.dylib (562.70.3) <37AF8EC6-BF34-3D15-BC3A-A9B98F2427D4> /usr/lib/system/libcorecrypto.dylib
    0x7fff795c5000 -     0x7fff795feff7  libdispatch.dylib (913.60.3) <BF368549-2DFB-3530-B4CB-31D5EDAC4F2F> /usr/lib/system/libdispatch.dylib
    0x7fff795ff000 -     0x7fff7961cff7  libdyld.dylib (551.5) <49BF9E96-8297-30CF-8AA6-128CC14054B2> /usr/lib/system/libdyld.dylib
    0x7fff7961d000 -     0x7fff7961dffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff7961e000 -     0x7fff7962aff3  libkxld.dylib (4570.71.35) <89E1A912-9AB7-3EFA-83B5-EB899F2E891F> /usr/lib/system/libkxld.dylib
    0x7fff7962b000 -     0x7fff7962bff7  liblaunch.dylib (1205.70.10) <ACB92462-EDA9-39E6-BB4E-635D47D30D58> /usr/lib/system/liblaunch.dylib
    0x7fff7962c000 -     0x7fff79630ffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff79631000 -     0x7fff79633ff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff79634000 -     0x7fff79635ff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff79636000 -     0x7fff7964dfff  libsystem_asl.dylib (356.70.1) <39E46A6F-B228-3E78-B83E-1779F9707A39> /usr/lib/system/libsystem_asl.dylib
    0x7fff7964e000 -     0x7fff7964efff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff7964f000 -     0x7fff796d8ff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff796d9000 -     0x7fff796dcffb  libsystem_configuration.dylib (963.50.9) <A5DC1AFC-2C3E-3113-BE20-48F96064DB0F> /usr/lib/system/libsystem_configuration.dylib
    0x7fff796dd000 -     0x7fff796e0ffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff796e1000 -     0x7fff796e2fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff796e3000 -     0x7fff796e9ff7  libsystem_dnssd.dylib (878.70.3) <B6E027BB-B4B1-37F4-9BBE-C2D299124CF3> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff796ea000 -     0x7fff79733ff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff79734000 -     0x7fff7975aff7  libsystem_kernel.dylib (4570.71.35) <63791C4B-6118-3D55-AA3F-5065B1345410> /usr/lib/system/libsystem_kernel.dylib
    0x7fff7975b000 -     0x7fff797a6fcb  libsystem_m.dylib (3147.50.1) <17570F46-566C-39FC-BEF6-635A355DD549> /usr/lib/system/libsystem_m.dylib
    0x7fff797a7000 -     0x7fff797c6ff7  libsystem_malloc.dylib (140.50.7) <A45A484C-3BDE-3BC4-A219-726E3CB332D9> /usr/lib/system/libsystem_malloc.dylib
    0x7fff797c7000 -     0x7fff798f7ff7  libsystem_network.dylib (1229.70.2) <5E86B2DE-9E15-3354-8714-4094ED5F698D> /usr/lib/system/libsystem_network.dylib
    0x7fff798f8000 -     0x7fff79902ffb  libsystem_networkextension.dylib (767.70.2) <9DC03712-552D-3AEE-9519-B5ED70980B70> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff79903000 -     0x7fff7990cff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff7990d000 -     0x7fff79914ff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff79915000 -     0x7fff79920fff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff79921000 -     0x7fff79924fff  libsystem_sandbox.dylib (765.70.1) <553DFCC6-9D31-3B9C-AB7C-30F6F265786D> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff79925000 -     0x7fff79926ff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff79927000 -     0x7fff7992eff7  libsystem_symptoms.dylib (820.60.3) <441C6CA0-5711-3BB1-8420-DDAC3D5272E1> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff7992f000 -     0x7fff79942fff  libsystem_trace.dylib (829.70.1) <3A6CB706-8CA6-3616-8AFC-14AAD7FAF187> /usr/lib/system/libsystem_trace.dylib
    0x7fff79944000 -     0x7fff79949ff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff7994a000 -     0x7fff79977ff7  libxpc.dylib (1205.70.10) <94028D4E-F0CB-3D6E-ACF6-9323631588B5> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 89261899
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=406.1M resident=0K(0%) swapped_out_or_unallocated=406.1M(100%)
Writable regions: Total=207.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=207.9M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        2 
Activity Tracing                   256K        2 
CG backing stores                 6056K        2 
CG image                            72K        3 
CoreGraphics                         8K        2 
CoreImage                           32K        5 
CoreUI image file                  180K        4 
Dispatch continuations            16.0M        2 
Kernel Alloc Once                    8K        2 
MALLOC                           160.2M       47 
MALLOC guard page                   48K        9 
Memory Tag 242                      12K        2 
STACK GUARD                       56.0M       12 
Stack                             13.1M       12 
VM_ALLOCATE                       1428K       14 
__DATA                            34.2M      283 
__FONT_DATA                          4K        2 
__GLSLBUILTINS                    2588K        2 
__LINKEDIT                       205.8M       48 
__TEXT                           200.3M      282 
__UNICODE                          560K        2 
mapped file                       60.8M       15 
shared memory                     3760K       15 
===========                     =======  ======= 
TOTAL                            761.2M      746 

Model: MacBookPro11,2, BootROM 151.0.0.0.0, 4 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 2.18f15
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.37.32.1a1)
Bluetooth: Version 6.0.7f12, 3 services, 27 devices, 1 incoming serial ports
Network Service: USB 10/100/1000 LAN, Ethernet, en4
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM1024F, 1 TB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: 
```

## Output from --test-audio:

```
❯ ./bin/vegastrike-engine -d../data --test-audio
[2021-08-29 18:43:56.957601] [0x00007fffb2044380] [trace]   Registering codec ogg
[2021-08-29 18:43:56.957983] [0x00007fffb2044380] [trace]   .

Legacy Mode: FALSE
 In path /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/bin
Vega Strike
See http://www.gnu.org/copyleft/gpl.html for license details.

ARG #1 = -d../data
Using data dir specified on command line : ../data
ARG #2 = --test-audio
GOT SUBDIR ARG =
Found data in ../data
Using /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data as data directory
Using .vegastrike as the home directory
Found MODDIR = /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/mods
USING HOMEDIR : /Users/dwales/.vegastrike As the home directory
CONFIGFILE - Found a config file in home directory, using : /Users/dwales/.vegastrike/vegastrike.config
DATADIR - No datadir specified in config file
Force galaxy to /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/universe/milky_way.xml
SIMULATION_ATOM: 0.01
Creating scene manager...OK
Running rendererless tests...
  Clearing Scene
  Creating empty inactive scene
  Clearing Scene
    destroying "testScene"...done
  Creating empty active scene
  Clearing Scene
    destroying "testScene"...done
Running rendererful tests...
  Initializing renderer...
Uncaught exception: OpenAL error: unknown(Bad value) at /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/engine/src/audio/renderers/OpenAL/OpenALRenderer.cpp:168
FAILED
```

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [X] (Mostly) Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

Issues:
- Please list any related issues
- Fixes #78 for 0.8.x
- Fixes #533 for 0.8.x (I think)

Purpose:
- What is this pull request trying to do? Introduce macOS support to the 0.8.x series of releases (making the game compilable, as well as playable)
- What release is this for? 0.8.x
- Is there a project or milestone we should apply this to? Not sure

### CODE REVIEW

**Comment by stephengtuggy** [comment]
The Windows CI builds are going to keep failing until I get that stuff updated. But otherwise, this PR should be good to go.

File: engine/src/cmd/collide2/opcodetypes.h [hunk 1]
```diff
@@ -171,7 +171,7 @@ typedef int ptrdiff_t;
 #define _PTRDIFF_T_DEFINED
 #endif
 
-#if !defined(CS_HAVE_INTMAX_T)
+#if !defined(CS_HAVE_INTMAX_T) && !__APPLE__
```
Comment (BenjamenMeyer) [inline engine/src/cmd/collide2/opcodetypes.h:174]: shouldn't that be `!defined(__APPLE__)`?

**Review by BenjamenMeyer — CHANGES_REQUESTED** [review]

File: engine/src/cmd/collide2/opcodetypes.h (hunk 1 above)
Comment (stephengtuggy) [reply engine/src/cmd/collide2/opcodetypes.h:174]: The two expressions are probably functionally equivalent. I.e., when `__APPLE__` is defined, it is generally defined to the value `1` or something similar. I saw code elsewhere on the web that used the type of expression I used here, and concluded that perhaps that is the more conventional or standard way to do it. But I am not 100% certain of that. If you like, I can certainly switch back to the `!defined(__APPLE__)` syntax we have used previously.

Comment (BenjamenMeyer) [reply engine/src/cmd/collide2/opcodetypes.h:174]: We use `!defined(__APPLE__)` elsewhere and should remain internally consistent at the very least; I think it's also clearer from a C Macro perspective as it's not required that these macros carry a value.

It's also consistent on the line since the first parameter is `!defined()` too.

Comment (stephengtuggy) [reply engine/src/cmd/collide2/opcodetypes.h]: Done ✔️

**Review by BenjamenMeyer — APPROVED** [review]
