### PR TITLE
Fix issue where some component damage can't be fixed

### LINKED ISSUE #916: Llama.begin is not upgraded in game when purchasing the first repair and refuel.
Just noticed this as well, and not in play testing pull request #896 

When starting a new campaign, and immediately purchasing the refuel and repair for your ship, set speed for the flight control computer is supposed to change from 120 to 125. That does not seem to happen anymore. 

I tested by saving a game, and loading that. 

Just for clarity, I am testing the latest master branches of Assets and Engine.

### PR DESCRIPTION
**Pull request by royfalk**
- Basic Repair to factor damage to these components
- Make Basic Repair also repair this damage

Please answer the following:

Code Changes:
- [x] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation _targeted. Focus on ship performance and general repair._

Issues:
- FTL drive damage not yet implemented properly - existing issue identified.

fix #916

### CODE REVIEW

File: engine/src/components/drive.cpp [hunk 1]
```diff
@@ -96,6 +96,12 @@ void Drive::Load(std::string upgrade_key,
 
     speed = Resource<double>(UnitCSVFactory::GetVariable(unit_key, "Default_Speed_Governor", std::string("0.0")), 
                                                          game_speed, minimal_drive_functionality);
+
+    operational = (yaw.Percent() + pitch.Percent() + roll.Percent() +
```
Comment (BenjamenMeyer) [inline engine/src/components/drive.cpp:100]: would be good to have a comment explaining this calculation

**Review by BenjamenMeyer — APPROVED** [review]
would be good to add a comment explaining the added calculation; but otherwise LGTM

**Comment by BenjamenMeyer** [comment]
Thanks for the comments!
