### PR TITLE
Fix/issue 335

### LINKED ISSUE #296: engine/src/universe_generic has a compile warning
[ 21%] Building CXX object CMakeFiles/engine_com.dir/src/universe_generic.cpp.o
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/universe_generic.cpp: In member function 'void Universe::clearAllSystems()':
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/universe_generic.cpp:36:9: warning: deleting object of polymorphic class type 'StarSystem' which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
   36 |         delete star_system.back();
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
[ 22%] Building CXX object CMakeFiles/engine_com.dir/src/universe_util_generic.cpp.o

### LINKED ISSUE #297: engine/src/universe.cpp has a compile warning
[ 52%] Building CXX object CMakeFiles/vegastrike.dir/src/universe.cpp.o
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/universe.cpp: In member function 'virtual void GameUniverse::StartDraw()':
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/universe.cpp:306:25: warning: deleting object of polymorphic class type 'StarSystem' which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
  306 |                         delete star_system.back();
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
[ 52%] Building CXX object CMakeFiles/vegastrike.dir/src/gfx/ani_texture.cpp.o

### LINKED ISSUE #335: Top speed in SPEC mode has dropped from 97C to <10C

### LINKED ISSUE #337: gl_light_state.cpp:426: void gfx_light::TrashFromGLLights(): Assertion `(GLLights[target].options&OpenGLL::GLL_ON) == 0' failed.

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [x] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
- Please list any related issues
**Closes #335**
**Closes #337**
**Closes #296**
**Closes #297**

Purpose:
- What is this pull request trying to do? **Restore the maximum SPEC speed to its previous value of ~97C**
- What release is this for? **0.7.0, probably**
- Is there a project or milestone we should apply this to? **0.7.x, probably**

### CODE REVIEW

**Comment by stephengtuggy** [comment]
I have fixed issue #335 , but ran into #337 in the process. #337 isn't totally fixed yet.

**Comment by stephengtuggy** [comment]
Note that #337 appears to be an existing issue, introduced in #326 , I believe.

File: engine/src/cmd/movable.cpp [hunk 1]
```diff
@@ -252,6 +232,13 @@ void Movable::Rotate( const Vector &axis )
 
 Vector Movable::ResolveForces( const Transformation &trans, const Matrix &transmat )
 {
+    static float maxplayerrotationrate = GameConfig::GetVariable( "physics", "maxplayerrot", 24);
+    static float maxnonplayerrotationrate = GameConfig::GetVariable( "physics", "maxNPCrot", 360);
+    static float warpstretchcutoff = GameConfig::GetVariable( "graphics", "warp_stretch_cutoff", 500000) * GameConfig::GetVariable( "physics", "game_speed", 1);
+    static float warpstretchoutcutoff = GameConfig::GetVariable( "graphics", "warp_stretch_decel_cutoff", 500000) * GameConfig::GetVariable( "physics", "game_speed", 1);
+    static float sec = GameConfig::GetVariable( "graphics", "insys_jump_ani_second_ahead", 4) / (GameConfig::GetVariable( "physics", "game_speed", 1) * GameConfig::GetVariable( "physics", "game_accel", 1));
+    static float endsec = GameConfig::GetVariable( "graphics", "insys_jump_ani_second_ahead_end",0.03f) /( GameConfig::GetVariable( "physics", "game_speed",1.0f) *GameConfig::GetVariable( "physics", "game_accel", 1.0f) );
```
Comment (BenjamenMeyer) [inline engine/src/cmd/movable.cpp:240]: NOTE: These are the kinds of things that I'd like to see be properties of the class and be initialized as part of the class being initialized. They can be static class members and be initialized the first time the class is initialized for all instances if desired.

```c++
class X
{
protected:
    static bool initialized = false;  // control variable for initialization logic
    static float endsec = 0.0;  // set default value
    ...
}


X::X()
{
   if (!X.initialized) {
       // Note - ideally this would be `config.GetVariable()` where `config` could be passed as an argument or be one of the sole/few global variables we have in the system
       X.endsec = GameConfig::GetVariable(...);
       X.initialized = true;
   }
}
```

I would like to see us move to this style as it would greatly reduce the number of times we have to load configuration data. It would also enable us to easily add a `loadConfig()` function that could be called whenever we needed to load or reload the configuration for the entire class.

Comment (stephengtuggy) [reply engine/src/cmd/movable.cpp:240]: I like that pattern. I will try implementing at least part of it. The global `config` variable I may leave for later.

Comment (BenjamenMeyer) [reply engine/src/cmd/movable.cpp:240]: yes that's fine. As a first step it'd be good to move to this pattern. Once all the code is on this pattern we can look at moving to the global config object too.

**Comment by evertvorster** [comment]
Hi there. 
I've been absent for a while. Real live getting in the way and all. I'm building this PR against master now, and will give it a good play test. 
Thanks all for all your hard work, and patience with slackers like me. :P

**Comment by stephengtuggy** [comment]
@evertvorster No problem. :-)

I have some more changes coming to this PR, just so you know.

File: engine/src/cmd/movable.cpp (hunk 1 above)
Comment (stephengtuggy) [reply engine/src/cmd/movable.cpp]: Done.

**Comment by stephengtuggy** [comment]
@evertvorster OK, I think this PR is ready for testing now. Thanks!

**Comment by stephengtuggy** [comment]
The graphics/motion actually seem smoother now! Let me know if you guys observe the same thing.

Maybe it's because the game isn't constantly loading config values from disk? LOL

File: engine/CMakeLists.txt [hunk 2]
```diff
@@ -531,9 +531,9 @@ IF (NOT BUILD_OPT)
     SET(BUILD_OPT -O2 CACHE STRING "-O0, -O1, -O2, -O3, -Os, -Ofast" FORCE )
 ENDIF (NOT BUILD_OPT)
 
-IF (CMAKE_COMPILER_IS_GNUCXX)
-    ADD_DEFINITIONS(-std=gnu++03)
-ENDIF ()
+# IF (CMAKE_COMPILER_IS_GNUCXX)
+#     ADD_DEFINITIONS(-std=gnu++03)
+# ENDIF ()
```
Comment (BenjamenMeyer) [inline engine/CMakeLists.txt:536]: I believe we're setting Cxx11 elsewhere so this can go away entirely.

**Review by BenjamenMeyer — APPROVED** [review]
One minor comment (not blocking); if we've sufficiently play tested this (I haven't had a chance) then we can merge.

File: engine/CMakeLists.txt (hunk 2 above)
Comment (stephengtuggy) [reply engine/CMakeLists.txt:536]: Yes. This can probably get done in a future PR.
