### PR TITLE
Detect whether on Linux or macOS using `uname` -- `master` branch

### LINKED ISSUE #1443: We do not currently have real OS detection logic for Linux vs. macOS
**Describe the bug**
For bootstrapping purposes, among other things, we need to follow different code paths for Linux vs. macOS vs. Windows. We should auto-detect which one we are running on, but we have no such functionality today. Instead, we just read an environment variable, `MY_OS_NAME`.

**To Reproduce**
You can probably fool the system into thinking it's on macOS simply by setting `MY_OS_NAME` to "darwin" or something.

**Expected behavior**
The bootstrap script should call `uname` or similar to auto-detect which operating system we are truly running on.

**Please complete the following information):**
 - OS: [e.g. iOS] All
 - Software Versions [e.g. 22] N/A

**Additional context**
This same issue applied to the Build System Docker Images, as well; see https://github.com/vegastrike/build-system-docker-images/issues/89

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [x] This is a CI/build system change only

Issues:
- Addresses #1443 on `master`

Purpose:
- What is this pull request trying to do? Detect properly which operating system we are on; fix #1443 on the `master` branch
- What release is this for? 0.10.x
- Is there a project or milestone we should apply this to? 0.10.x

### CODE REVIEW

File: script/bootstrap [hunk 1]
```diff
@@ -30,1133 +30,40 @@
...
 
 echo "------------------------------"
-echo "--- bootstrap | 2025-11-16 ---"
+echo "--- bootstrap | 2025-11-27 ---"
 echo "------------------------------"
 
-UPDATE_ALL_SYSTEM_PACKAGES="$1"
+platform="$(uname | tr '[:upper:]' '[:lower:]')"
 
-if [ -f /etc/os-release ]
```
Comment (stephengtuggy) [inline script/bootstrap:38]: Linux-specific logic moved to bootstrap-on-linux.sh

File: script/bootstrap-on-linux.sh [hunk 2]
```diff
@@ -0,0 +1,1162 @@
...
+else
+    echo "os-release file not found; unable to continue"
+    exit 1
+fi
+LINUX_ID=$(grep ^ID= $OS_RELEASE_LOCATION | sed 's/^ID=//' | tr -d '"\n')
+echo "LINUX_ID = ${LINUX_ID}"
+LINUX_CODENAME=$(grep ^VERSION_CODENAME= $OS_RELEASE_LOCATION | sed 's/^VERSION_CODENAME=//' | tr -d '"\n')
+echo "LINUX_CODENAME = ${LINUX_CODENAME}"
+LINUX_VERSION_ID=$(grep ^VERSION_ID= $OS_RELEASE_LOCATION | sed 's/^VERSION_ID=//' | tr -d '"\n')
+echo "LINUX_VERSION_ID = ${LINUX_VERSION_ID}"
```
Comment (BenjamenMeyer) [inline script/bootstrap-on-linux.sh:53]: FYI- there's a tool `lsb_release` that technically is supposed to report all the info in `/etc/lsb-release`/`/etc/os-release` which should provide all this information. I didn't use it before because I've had little success with figuring it out myself, but it's probably a better mechanism than parsing the files ourselves. $0.02 in case you wanted to pursue it, but not blocking...

Then again, reading through https://www.freedesktop.org/software/systemd/man/latest/os-release.html and https://0pointer.de/blog/projects/os-release this seems to be replacing the LSB utilities, and the examples on freedesktop.org show it being just sourced in:
```
Example 3. Reading os-release in [sh(1)](https://man7.org/linux/man-pages/man1/sh.1.html)

#!/bin/sh -eu
# SPDX-License-Identifier: MIT-0

test -e /etc/os-release && os_release='/etc/os-release' || os_release='/usr/lib/os-release'
. "${os_release}"

echo "Running on ${PRETTY_NAME:-Linux}"

if [ "${ID:-linux}" = "debian" ] || [ "${ID_LIKE#*debian*}" != "${ID_LIKE}" ]; then
    echo "Looks like Debian!"
fi
```
so we might just do that instead of trying to parse them out of the file.

**Review by BenjamenMeyer — APPROVED** [review]
