### PR TITLE
Fix issue preventing player from dying

### LINKED ISSUE #600: When the ship is destroyed, the pilot should auto-eject some of the time.
Currently, it looks like the pilot auto-ejects all/most of the time. This does not appear to be the correct behavior.

**Required**

1. Find the old code and figure out the correct ratio.
2. Find the new code and fix the ratio to match.

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [In Progress] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
- Please list any related issues
- Closes #600 

Purpose:
- What is this pull request trying to do? Fix #600 , the issue where the player simply can't die
- What release is this for? 0.9.x
- Is there a project or milestone we should apply this to? 0.9.x

### CODE REVIEW

File: engine/src/cmd/damageable.cpp [hunk 1]
```diff
@@ -251,10 +251,8 @@ void Damageable::ApplyDamage( const Vector &pnt,
         static bool player_autoeject =
                 GameConfig::GetVariable( "physics", "player_autoeject", true );
 
-        if(shot_at_is_player && player_autoeject) {
-            unit->EjectCargo( (unsigned int) -1 );
-        } else if(rand() < (RAND_MAX*auto_eject_percent) && unit->isUnit() == _UnitType::unit &&
-                  unit->faction != neutralfac && unit->faction != upgradesfac) {
+        if (shot_at_is_player && player_autoeject && rand() < (RAND_MAX*auto_eject_percent)
```
Comment (royfalk) [inline engine/src/cmd/damageable.cpp:254]: This will only apply to the player. The current behavior is that other units auto eject some of the time.

Comment (stephengtuggy) [reply engine/src/cmd/damageable.cpp:254]: Not sure I follow?

Comment (royfalk) [reply engine/src/cmd/damageable.cpp:254]: The deleted code was split in two:
if(player && player_auto_eject) eject
else something...

Your new code has merged both so the if statement will only apply to the player ship. Other pilots will not eject.

Comment (stephengtuggy) [reply engine/src/cmd/damageable.cpp:254]: Hmm. You're probably right. Let me try this again

File: engine/src/cmd/damageable.cpp [hunk 2]
```diff
@@ -247,15 +247,26 @@ void Damageable::ApplyDamage( const Vector &pnt,
...
+                VS_LOG(debug, "Not auto ejecting player");
+            }
+        } else {
+            if (unit->isUnit() == _UnitType::unit
+                    && rand() < (RAND_MAX * auto_eject_percent)) {
+                VS_LOG(debug, "Auto ejecting NPC");
+                unit->EjectCargo( (unsigned int) -1 );
+            } else {
+                VS_LOG(debug, "Not auto ejecting NPC");
+            }
```
Comment (stephengtuggy) [inline engine/src/cmd/damageable.cpp:269]: OK, try it now?

I tested this code just now, and I was able to confirm that all four cases were exercised:

1. Auto ejecting NPC
2. Not auto ejecting NPC
3. Auto ejecting player
4. Not auto ejecting player

Comment (royfalk) [reply engine/src/cmd/damageable.cpp:269]: OK. This looks good and I'll approve it.

I have some minor nitpicks:

- This is very readable but I'd shorten it and lose readability for something like:
`if(unit->isUnit && ((shot_at_is_player && player_auto_eject) || !shot_at_is_player)`
   This would collapse a lot of the code into something shorter. But, like I said, it's a balance and taste issue.
- I just realized that the if (unit->isUnit() == _UnitType::unit) is potentially going to be a big issue moving forward. If we move ships to their own class as we should and is planned, we'll need to go through the code and find all these instances.

Comment (royfalk) [reply engine/src/cmd/damageable.cpp:269]: Oops. I can't approve as I'm not a reviewer.

Comment (stephengtuggy) [reply engine/src/cmd/damageable.cpp:269]: I just re-requested a review from you, @royfalk . Hopefully that allows you to approve it.

File: engine/src/cmd/damageable.cpp [hunk 3]
```diff
@@ -247,15 +247,26 @@ void Damageable::ApplyDamage( const Vector &pnt,
...
                 GameConfig::GetVariable( "physics", "player_autoeject", true );
 
-        if(shot_at_is_player && player_autoeject) {
-            unit->EjectCargo( (unsigned int) -1 );
-        } else if(rand() < (RAND_MAX*auto_eject_percent) && unit->isUnit() == _UnitType::unit &&
-                  unit->faction != neutralfac && unit->faction != upgradesfac) {
-            unit->EjectCargo( (unsigned int) -1 );
+        if (shot_at_is_player) {
+            if (player_autoeject
+                    && rand() < (RAND_MAX * auto_eject_percent)) {
```
Comment (BenjamenMeyer) [inline engine/src/cmd/damageable.cpp:256]: This would be better as a function of some sort, especially since you use it twice right here - or calculate it ahead of time and store in a variable

**Review by BenjamenMeyer — APPROVED** [review]
Would prefer the rand lines be less duplicative, but not going to block on it.
