### PR TITLE
Fix resume crash on 0.6.x

### LINKED ISSUE #28: Game crashes when paused, can't resume
### Observed behaviour

When game is put in pause ('Pause' key) during flight it freezes and cannot be resumed.

Once killed:
```
Traceback (most recent call last):
  File "/home/andre/Build/Assets-Production/modules/missions/privateer.py", line 34, in Execute
    i.Execute()
  File "/home/andre/Build/Assets-Production/modules/random_encounters.py", line 291, in Execute
    dynamic_battle.UpdateCombatTurn()
  File "/home/andre/Build/Assets-Production/modules/dynamic_battle.py", line 42, in UpdateCombatTurn
    lookorsiege=LookForTrouble (fac)
  File "/home/andre/Build/Assets-Production/modules/dynamic_battle.py", line 369, in LookForTrouble
    randomMovement (i,faction)
  File "/home/andre/Build/Assets-Production/modules/dynamic_battle.py", line 275, in randomMovement
    fg_util.TransferFG( fg,fac,suggestednewsys);
  File "/home/andre/Build/Assets-Production/modules/fg_util.py", line 424, in TransferFG
    starsystem=Director.getSaveString(ccp,key,1)
KeyboardInterrupt
terminate called after throwing an instance of 'boost::python::error_already_set'
```
### Expected behaviour
Game is put in pause and resumed with 'Pause' key

Vega Strike 0.5.3 (current master) on Arch Linux x86_64

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [x] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
Closes #28 

Purpose:
- What is this pull request trying to do? **Make it so that users can pause and resume the game freely, without crashes.**
- What release is this for? **0.6.0**
- Is there a project or milestone we should apply this to? **0.6.x**

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
Can confirm that the game does unpause - yeah!
It pauses pretty quickly but does take a little bit to unpause.

**Comment by BenjamenMeyer** [comment]
I've done everything in our PR Game Play checklist, and can confirm the pause/resume is fixed.

**Comment by stephengtuggy** [comment]
> I've done everything in our PR Game Play checklist, and can confirm the pause/resume is fixed.

Awesome! Thanks! This PR is ready for review then.

File: engine/src/cmd/ai/firekeyboard.cpp [hunk 1]
```diff
@@ -529,9 +529,12 @@ void FireKeyboard::ECMKey( const KBData&, KBSTATE k )
...
 void FireKeyboard::FireKey( const KBData&, KBSTATE k )
 {
-    if (g().firekey == DOWN && k == UP)
+    if (g().firekey == DOWN && k == UP) {
         return;
-    if (k == UP && g().firekey == RELEASE) {} else {
+    }
+    if (k == UP && g().firekey == RELEASE) {
+        
+    } else {
```
Comment (BenjamenMeyer) [inline engine/src/cmd/ai/firekeyboard.cpp:537]: This is the crux of the fix, no?

Comment (stephengtuggy) [inline engine/src/cmd/ai/firekeyboard.cpp:537]: This is just reformatting so I could understand better what was going on.

File: engine/src/cmd/ai/firekeyboard.cpp [hunk 2]
```diff
@@ -732,8 +735,10 @@ void FireKeyboard::NearestJumpKey( const KBData&, KBSTATE k )
 
 void FireKeyboard::TogglePause( const KBData&, KBSTATE k )
 {
-    if (g().togglepausekey != PRESS)
+    if (k == PRESS) {
+        VSFileSystem::vs_dprintf(1, "FireKeyboard::TogglePause(): Pause key detected\n");
         g().togglepausekey = k;
+    }
```
Comment (stephengtuggy) [inline engine/src/cmd/ai/firekeyboard.cpp:741]: Again, just reformatting, plus debug output.

File: engine/src/cmd/ai/firekeyboard.cpp [hunk 3]
```diff
@@ -1873,15 +1878,18 @@ void FireKeyboard::Execute()
...
-	}
+        {
+            VSFileSystem::vs_dprintf(1, "Calling _Universe->AccessCockpit()->OnPauseBegin();\n");
+            _Universe->AccessCockpit()->OnPauseBegin();
+        }
+        else
+        {
+            VSFileSystem::vs_dprintf(1, "Calling _Universe->AccessCockpit()->OnPauseEnd();\n");
+            _Universe->AccessCockpit()->OnPauseEnd();
+        }
```
Comment (stephengtuggy) [inline engine/src/cmd/ai/firekeyboard.cpp:1892]: Once again, just reformatting plus debug output

File: engine/src/lin_time.cpp [hunk 4]
```diff
@@ -113,15 +113,18 @@ void setTimeCompression( float tc )
...
+        fprintf(stderr, "toggle_pause() in lin_time.cpp: Resuming (unpausing)\n");
         setTimeCompression(1);
         paused = false;
     }
     else
     {
-        setTimeCompression(.0000001);
-	paused = true;
+        fprintf(stderr, "toggle_pause() in lin_time.cpp: Pausing\n");
+        setTimeCompression(.00001);
```
Comment (stephengtuggy) [inline engine/src/lin_time.cpp:126]: This is the crux of the fix here. Apparently, when time compression is set to a very low value, it has the effect of slowing the entire game down -- including processing keystrokes. The game "pauses" by slowing itself down drastically. Then it "resumes", or unpauses, by returning to normal speed.

The problem was the time compression coefficient. It was being set so slow that the "resume" key never registered. Neither did anything else. Or at least, not for probably hours and hours.

So I simply changed the coefficient by a couple of orders of magnitude, and problem solved. That was the fix, best I can tell.

File: engine/src/cmd/ai/firekeyboard.cpp (hunk 1 above)
Comment (stephengtuggy) [reply engine/src/cmd/ai/firekeyboard.cpp:537]: Actually, no. That's just reformatting. Sorry if it's a bit confusing.

See my review below for an explanation of where the fix is. It's in lin_time.cpp, on line 126.

File: engine/CMakeLists.txt [hunk 5]
```diff
@@ -572,9 +572,9 @@ IF (POLICY CMP0072)
   CMAKE_POLICY (SET CMP0072 NEW)
 ENDIF ()
 
-# Set the default build type to Release
+# Set the default build type to Debug
 IF (NOT CMAKE_BUILD_TYPE)
-    SET(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "Release, Debug, Profiler" FORCE )
```
Comment (nabaco) [inline engine/CMakeLists.txt:577]: Why do we want this change as part of this PR?

File: engine/src/lin_time.cpp (hunk 4 above)
Comment (BenjamenMeyer) [reply engine/src/lin_time.cpp:126]: It would be good to have a comment here about that so we don't do that again.

We might even need to make that CPU dependent...not in this resolution though.

File: engine/CMakeLists.txt (hunk 5 above)
Comment (stephengtuggy) [reply engine/CMakeLists.txt:577]: This change is really incidental to the main purpose of the PR. I saw something that looked important to fix, and fixed it. We can move it into a separate PR if you feel it's necessary.

File: engine/src/lin_time.cpp (hunk 4 above)
Comment (stephengtuggy) [reply engine/src/lin_time.cpp:130]: > It would be good to have a comment here about that so we don't do that again.
> 
> We might even need to make that CPU dependent...not in this resolution though.

@BenjamenMeyer Comment added.
